### ISSUE TITLE
linux系统上调用动态库报错

### ISSUE THREAD

**Issue by xlei1123** [zhangyuang/node-ffi-rs#1]
报错：
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DlOpen { desc: "./libprnGENLOT.so: wrong ELF class: ELFCLASS32" }', src/lib.rs:55:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
已放弃（核心已转储）

**Comment by zhangyuang** [comment]
这个看起来是so文件的编译环境和运行环境不一样，请保持环境一致

**Comment by zhangyuang** [comment]
你的系统是 64 位的，但是你尝试加载的动态链接库是 32 位的。这种情况下，你需要确保使用与你的系统架构匹配的动态链接库。

**Comment by xlei1123** [comment]
> 你的系统是 64 位的，但是你尝试加载的动态链接库是 32 位的。这种情况下，你需要确保使用与你的系统架构匹配的动态链接库。

好的 谢谢

**Comment by snakeXiang** [comment]
> 你的系统是 64 位的，但是你尝试加载的动态链接库是 32 位的。这种情况下，你需要确保使用与你的系统架构匹配的动态链接库。

uname -a
Linux localhost.localdomain 4.0.4-genlot #9 SMP Wed Oct 19 03:50:12 EDT 2016 i686 i686 i386 GNU/Linux
刚刚查了一下 我的系统是32位的
