### ISSUE TITLE
Can not assign value through pointer in dynamic link library side

### ISSUE THREAD

**Issue by ColourfulBlack** [zhangyuang/node-ffi-rs#13]
### test.cpp
```C++
struct Result {
  int c;
};

extern "C" void sum(int a, int b, Result* result) { 
  result->c= a+b;
}

```
build script
```terminal
g++ --std=c++20 -shared test.cpp -o libtest.so
```

### main.js
```js
import { load, DataType, open, close, arrayConstructor } from "ffi-rs";

const a = 1;
const b = 10;
const dynamicLib = "./libtest.so";


open({
  library: "libtest", // key
  path: dynamicLib, // path
});
const ResultType = { c: DataType.I32 };

let result = {
  c: 0,
};

load({
  library: "libtest", // path to the dynamic library file
  funcName: "sum", // the name of the function to call
  retType: DataType.Void, // the return value type
  paramsType: [DataType.I32, DataType.I32, ResultType], // the parameter types
  paramsValue: [a, b, result], // the actual parameter values
});
console.log(result.c);
// release library memory when you're not using it.
close("libtest");
```

### result
`console.log(result.c)` logs `0`.

### My question
Many C Libraries use pointer to pass result out, especially when one function wants to return multiple results `void fun(int* out1, int* out2, int* out3)`. Kinda like `out parameter` in `C#`.

A normal `C` program invoke a `C` dll, pass a pointer to a function inside `C` dll, that function should be able to change the member value of which struct this pointer pointing to. But according to my test, `node-ffi-rs` doesn't work like that. 

Is this **by design**? Or **on progress**? Thanks for any help.

**Comment by ColourfulBlack** [comment]
I see, I should use `createPointer` to create a pointer and pass it to that function ,then use `restorePointer` to restore the value. Sorry about my careless.

**Comment by GedorN** [comment]
Can someone help me? I am really struggling to understand how to return a simple value from a C pointer in this test function.
```c++
extern "C" int32_t get_from_pointer(int32_t *c) {
    int x = 10;
    int y = 25;
    *c = x + y;

    return x + y;
}
```
I am loading the function this way:
```js
  const v = load({
      library: "libsum", // path to the dynamic library file
      funcName: 'get_from_pointer', // the name of the function to call
      retType: DataType.I32, // the return value type
      paramsType: [DataType.I32], // the parameter types
      paramsValue: [ret]
  });

```

Currently, I am trying `ret` like this:
```js
 let ret = createPointer({
      paramsType: [DataType.I32Array],
      paramsValue: []
  })
```
