### ISSUE TITLE
What's wrong with the master branch?

### ISSUE THREAD

**Issue by ColourfulBlack** [zhangyuang/node-ffi-rs#14]
What's wrong with the master branch? Why did you overwrite all the code? 
<img width="1344" alt="image" src="https://github.com/zhangyuang/node-ffi-rs/assets/58283275/d9888274-394c-46e7-b14c-17efb004a1bb">

**Comment by ColourfulBlack** [comment]
@zhangyuang Do you plan to archive this repository?

**Comment by zhangyuang** [comment]
ffi-rs will continue to be updated, but the source code will not be released at this time. You can still download the latest binaries via npm. The readme will be updated in real time. The source code will be re-released later

**Comment by zhangyuang** [comment]
@ColourfulBlack

**Comment by ColourfulBlack** [comment]
Alright.
