### ISSUE TITLE
How to use with c++ `HANDLE*`

### ISSUE THREAD

**Issue by codering** [zhangyuang/node-ffi-rs#15]
c++  code
```c++
int OpenDevice(HANDLE* hComm, char* strComm) {

  *hComm = pProto->OpenDevice(strComm,lpCommPara);
  if (*hComm == FALSE || *hComm == INVALID_HANDLE_VALUE)
  {
	return E_DRV_OPENPORT_FAILED;
  }
  return E_DRV_SUCCESS;

}
```

**Comment by zhangyuang** [comment]
you can use createPointer



发自我的iPhone


------------------ Original ------------------
From: Justin ***@***.***&gt;
Date: Tue,Mar 19,2024 7:29 PM
To: zhangyuang/node-ffi-rs ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] How to use with c++ `HANDLE*` (Issue #15)





 
c++  code
 int OpenDevice(HANDLE* hComm, char* strComm) {   *hComm = pProto-&gt;OpenDevice(strComm,lpCommPara);   if (*hComm == FALSE || *hComm == INVALID_HANDLE_VALUE)   { 	return E_DRV_OPENPORT_FAILED;   }   return E_DRV_SUCCESS; }
