### ISSUE TITLE
How to call prctl

### ISSUE THREAD

**Issue by menelai** [zhangyuang/node-ffi-rs#19]
Hello my friend! Please help me.

In ffi-napi, the call was:
```typescript
import {Library} from 'ffi-napi';
const current = Library(null, {prctl: ['int32', ['int32', 'uint32']]});

current.prctl(1, 15);
```

How can I write the same with ffi-rs?

**Comment by zhangyuang** [comment]
after open library，use DataType.i32 as paramsType，DataType.void as retType



发自我的iPhone


------------------ Original ------------------
From: menelai ***@***.***&gt;
Date: Tue,Apr 2,2024 10:01 PM
To: zhangyuang/node-ffi-rs ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] How to call prctl (Issue #19)





 
Hello my friend! Please help me.
 
In ffi-napi, the call was:
 import {Library} from 'ffi-napi'; const current = Library(null, {prctl: ['int32', ['int32', 'uint32']]}); current.prctl(1, 15);
 
How can I write the same with ffi-rs?

**Comment by zhangyuang** [comment]
```js
open({
  library: 'libsum', // key
  path: dynamicLib // path
})

load({
  library: "libsum", // path to the dynamic library file
  funcName: 'sum', // the name of the function to call
  retType: DataType.I32, // the return value type
  paramsType: [DataType.I32, DataType.U32], // the parameter types
  paramsValue: [1, 15] // the actual parameter values
})
```

**Comment by Gobie** [comment]
`ffi-napi` enables accessing just functions in the current process by passing a `null` as library path: `Library(null, {prctl: ....)`). Is there a way to access these functions in `ffi-rs`?

**Comment by zhangyuang** [comment]
> `ffi-napi` enables accessing just functions in the current process by passing a `null` as library path: `Library(null, {prctl: ....)`). Is there a way to access these functions in `ffi-rs`?

Great feedback.I will provide the similar feature in the future after thinking

**Comment by menelai** [comment]
```typescript
open({
  library: 'sys', // key
  path: '', // path
});

load({
  library: 'sys',
  funcName: 'prctl',
  retType: DataType.I32,
  paramsType: [DataType.I32, DataType.I32],
  paramsValue: [
    1, // PR_SET_PDEATHSIG
    15, // SIGTERM
  ],
});
```

Looks like it works this way, is't it?

**Comment by zhangyuang** [comment]
It's correct

**Comment by zhangyuang** [comment]
> `ffi-napi` enables accessing just functions in the current process by passing a `null` as library path: `Library(null, {prctl: ....)`). Is there a way to access these functions in `ffi-rs`?

Goods news, in `ffi-rs@1.0.53`, you can get main program handle by pass an emptry string to `ffi-rs`. The usage has been updated in the latest readme

### Load Main Program handle

You can alse pass emptry path string in `open` function like [ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi?tab=readme-ov-file#example) to get the main program handle refer [dlopen](https://man7.org/linux/man-pages/man3/dlopen.3.html)

```js
open({
  library: "libnative",
  path: "",
});
// In darwin/linux, you can call atoi function which is includeed in the basic c library
equal(
  load({
    library: "libnative",
    funcName: "atoi",
    retType: DataType.I32,
    paramsType: [DataType.String],
    paramsValue: ["1000"],
  }),
  1000,
);
```
