### ISSUE TITLE
看起来挺好的，什么时候能有企业级可用的水平呢？

### ISSUE THREAD

**Issue by dbssAlan** [zhangyuang/node-ffi-rs#2]
公司的项目，不太敢用🤣，不过有这个项目挺好的

**Comment by zhangyuang** [comment]
这个很容易在项目里验证有效性吧，又不是框架级别的东西改动幅度很小



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 黯墨 ***@***.***&gt;
发送时间: 2023年8月19日 01:08
收件人: zhangyuang/node-ffi-rs ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/node-ffi-rs] 看起来挺好的，什么时候能有企业级可用的水平呢？ (Issue #2)





 
公司的项目，不太敢用🤣，不过有这个项目挺好的

**Comment by dbssAlan** [comment]
> 这个很容易在项目里验证有效性吧，又不是框架级别的东西改动幅度很小 发自我的iPhone

确实如此，但依旧会担心引入未知的问题，毕竟没有接触过Rust。已经采用child_process调用exe的方式了，之后功能优化会考虑尝试

**Comment by zhangyuang** [comment]
exe是可执行文件 跟动态链接库还是不一样的，ffi是用来调用具体的函数拿到返回值的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 黯墨 ***@***.***&gt;
发送时间: 2023年8月19日 01:17
收件人: zhangyuang/node-ffi-rs ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/node-ffi-rs] 看起来挺好的，什么时候能有企业级可用的水平呢？ (Issue #2)





  
这个很容易在项目里验证有效性吧，又不是框架级别的东西改动幅度很小 发自我的iPhone
  
确实如此，但依旧会担心引入未知的问题，毕竟没有接触过Rust。已经采用child_process调用exe的方式了，之后功能优化会考虑尝试

**Comment by dbssAlan** [comment]
> exe是可执行文件 跟动态链接库还是不一样的，ffi是用来调用具体的函数拿到返回值的 发自我的iPhone

是的，不过只是一个基于electron的客户端上很简单的网络检索的需求，无需传参，用了cJSON打印了输出，能跑通。要是再复杂的C语言需求我也整不出来了。后续如果功能优化，或者方案优化，可能再考虑直接调用dll。

**Comment by zhangyuang** [comment]
你如果要在electron客户端应用而不是node服务端应用需要保证动态库的编译环境与运行环境一致。可能需要编译多个环境的版本的动态库按需加载



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 黯墨 ***@***.***&gt;
发送时间: 2023年8月19日 01:23
收件人: zhangyuang/node-ffi-rs ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/node-ffi-rs] 看起来挺好的，什么时候能有企业级可用的水平呢？ (Issue #2)





  
exe是可执行文件 跟动态链接库还是不一样的，ffi是用来调用具体的函数拿到返回值的 发自我的iPhone
  
是的，不过只是一个基于electron的客户端上很简单的网络检索的需求，无需传参，用了cJSON打印了输出，能跑通。要是再复杂的C语言需求我也整不出来了。后续如果功能优化，或者方案优化，可能再考虑直接调用dll。

**Comment by dbssAlan** [comment]
> 你如果要在electron客户端应用而不是node服务端应用需要保证动态库的编译环境与运行环境一致。可能需要编译多个环境的版本的动态库按需加载 发自我的iPhone

是的，先上一版看看，目前也没要求可移植性
