### ISSUE TITLE
Running into Docker with Alpine

### ISSUE THREAD

**Issue by alextarana** [zhangyuang/node-ffi-rs#21]
I received this error if I try to use the package inside Docker with Alpine Linux:

```
Error: Cannot find module '@yuuang/ffi-rs-linux-x64-musl'
```

**Comment by zhangyuang** [comment]
Thanks for you feedback , `ffi-rs` only support `linux-x64-gnu` platform. I will support `linux-x64-musl`  immediately

**Comment by alextarana** [comment]
@zhangyuang Thank you so much!

**Comment by zhangyuang** [comment]
Support `linux-x64-musl` by `ffi-rs@1.0.52`
