### ISSUE TITLE
`setsockopt` returns -1, but we are unable to access `errno`

### ISSUE THREAD

**Issue by Gobie** [zhangyuang/node-ffi-rs#22]
Hey,
I have a minimal example below which returns `-1` when `setsockopt` is called.
I guess I am not working correctly with the pointers. Do you have any idea why?

I also can't find a way to access `errno` which would contain the error code. `ffi-napi` has `FFI.errno()` for that.

```
const os = require('os')
const { Socket } = require('net')
const { load, open, DataType, createPointer } = require('ffi-rs')

const SOL_TCP = 6
const platform = os.platform()
const TCP_KEEPINTVL = platform === 'darwin' ? 0x101 : platform === 'freebsd' ? 512 : 5

open({library: 'libnative', path: ''})

const setsockopt = (socket, level, option, value) => {
	const pointer = createPointer({
		paramsType: [DataType.I32],
		paramsValue: [value],
	})

	// int setsockopt(int socket, int level, int option_name, const void *option_value, socklen_t option_len);
	return load({
		library: 'libnative',
		funcName: 'setsockopt',
		retType: DataType.I32,
		paramsType: [DataType.I32, DataType.I32, DataType.I32, DataType.External, DataType.I32],
		paramsValue: [socket._handle?.fd, level, option, pointer[0], 4],
	})
}

const socket = new Socket()
socket.connect(80, 'google.com')
socket.on('connect', () => {
	console.log(setsockopt(socket, SOL_TCP, TCP_KEEPINTVL, 10))
})
socket.end()
```

**Comment by zhangyuang** [comment]
The issue was fixed in `ffi-rs@1.0.54`, you can try again with the latest depenency

**Comment by hertzg** [comment]
I'm a bit confused with how is this considered fixed?

How can we access `errno` from node?

**Comment by zhangyuang** [comment]
You can read the latest readme about pointer

**Comment by hertzg** [comment]
I've read the latest pointers readme and it has no mention of errno or similar enough example. Maybe I'm missing something but could you give a small code sample how to read `errno`?

**Comment by zhangyuang** [comment]
The latest version define the behavior about `pointer`  but `errno` hasn't been supported in `ffi-rs`, i will add the feature in a later version

**Comment by hertzg** [comment]
Thank you! Should we re-open this issue or create a new one?

**Comment by zhangyuang** [comment]
Create a new issue about support `errno` feature is better
