### ISSUE TITLE
Getting a buffer back from output - adapting from ref.refType(ref.types.void) usage in ffi-napi

### ISSUE THREAD

**Issue by AlexMakiJokela** [zhangyuang/node-ffi-rs#23]
Hi - thank you for picking up the pieces on ffi-napi! 

We're running into some issues trying to get back a Buffer which with ffi-napi was typed as: 
export const streamInfo = ref.refType(ref.types.void) - we're trying to use DataType.External for this with ffi-rs and just getting back an empty object.

here is the source we’re trying to access (by running lsl_create_streaminfo): https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/lsl_streaminfo_c.cpp#L20
here is the implementation of create_object_noexcept: https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/lsl_c_api_helpers.hpp#L81
GitHubGitHub
[liblsl/src/lsl_streaminfo_c.cpp at 6a85d6f969163cbc17b94b9bd088b972a09a881e · sccn/liblsl](https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/lsl_streaminfo_c.cpp#L20)
C++ lsl library for multi-modal time-synched data transmission over the local network - sccn/liblsl (119 kB)
https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/lsl_streaminfo_c.cpp#L20

GitHubGitHub
[liblsl/src/lsl_c_api_helpers.hpp at 6a85d6f969163cbc17b94b9bd088b972a09a881e · sccn/liblsl](https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/lsl_c_api_helpers.hpp#L81)
C++ lsl library for multi-modal time-synched data transmission over the local network - sccn/liblsl (119 kB)
https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/lsl_c_api_helpers.hpp#L81

[1:24](https://lumenalabs.slack.com/archives/D05HJ4EDV8V/p1712345047045499)
here is our attempt:
export const streamInfo = DataType.External

open({
			library: 'liblsl',
			path,
		})

const result = load({
					library: 'liblsl',
					funcName: 'lsl_create_streaminfo',
					retType: streamInfo,
					paramsType: [
						DataType.String,
						DataType.String,
						DataType.I32,
						DataType.Double,
						DataType.I32,
						DataType.String,
					],
					paramsValue: [
						name,
						type,
						channelCount,
						sampleRate,
						channelFormat,
						sourceId,
					],
				})
[1:25](https://lumenalabs.slack.com/archives/D05HJ4EDV8V/p1712345133848169)
here is the lsl_streaminfo interface: https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/api_types.hpp#L25
GitHubGitHub
[liblsl/src/api_types.hpp at 6a85d6f969163cbc17b94b9bd088b972a09a881e · sccn/liblsl](https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/api_types.hpp#L25)
C++ lsl library for multi-modal time-synched data transmission over the local network - sccn/liblsl (119 kB)
https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/api_types.hpp#L25

[1:26](https://lumenalabs.slack.com/archives/D05HJ4EDV8V/p1712345181915449)
here is the lsl_streaminfo_impl: https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/stream_info_impl.cpp#L26
GitHubGitHub
[liblsl/src/stream_info_impl.cpp at 6a85d6f969163cbc17b94b9bd088b972a09a881e · sccn/liblsl](https://github.com/sccn/liblsl/blob/6a85d6f969163cbc17b94b9bd088b972a09a881e/src/stream_info_impl.cpp#L26)
C++ lsl library for multi-modal time-synched data transmission over the local network - sccn/liblsl (119 kB)

Here is how we had it implemented in ffi-napi:
Types: https://github.com/neurodevs/node-lsl/blob/main/src/nodeLsl.types.ts (all the way at the bottom)
Code: https://github.com/neurodevs/node-lsl/blob/main/src/implementations/Liblsl.ts (loadBindings)

**Comment by zhangyuang** [comment]
Maybe you can try again with `ffi-rs@1.0.54`? I fixed some pointer bugs in the version , if it still fails, you can provide a minimal reproduction

**Comment by AlexMakiJokela** [comment]
That worked - thank you!!
