### ISSUE TITLE
[error]: uncaughtException: Cannot find module 'node-ffi-rs-linux-x64-gnu' 

### ISSUE THREAD

**Issue by lingyuj** [zhangyuang/node-ffi-rs#24]
What does this error mean? I tried to import ffi-rs on Ubuntu 20.04

**Comment by zhangyuang** [comment]
Please provide more detailed info and reproduction code, `ffi-rs` support `linux-x64-gnu` platform

**Comment by zhangyuang** [comment]
The latest module name is `ffi-rs` rather than `node-ffi-rs`

**Comment by lingyuj** [comment]
> The latest module name is `ffi-rs` instead of`node-ffi-rs`

Thanks. I used the old module. Will try the latest one.
