### ISSUE TITLE
Feature request to expose `errno`

### ISSUE THREAD

**Issue by hertzg** [zhangyuang/node-ffi-rs#27]
Hello following our short conversation in #22 I'm creating a separate issue to expose `errno`.

## Summary

Some syscall functions like `setsockopt` and simiar return `-1` but set the `errno` to actual error.
Currently there's no way to access this `errno` value. `ffi-napi` exposes this via `FFI.errno()` function call.

## Motivation

Since node v20.12.x broke `ffi-napi` and it seems like `ffi-napi` is not supported, I'm trying to migrate `net-keepalive` to `ffi-rs` one of the blockers is the lack of `errno`. Without it we can't provide clear enough error message on why `setsockopt` failed.
 

References:
* https://github.com/hertzg/node-net-keepalive/issues/313
* https://github.com/nodejs/node/issues/52229
* https://github.com/node-ffi-napi/node-ffi-napi/issues/269

**Comment by zhangyuang** [comment]
Support `errno` in `ffi-rs@1.0.60`

By default, `ffi-rs` will not output errno info, developers can get it by pass `errno: true` when call `open` method like 

```js
 const foo = load({
    library: 'libnative',
    funcName: 'setsockopt',
    retType: DataType.I32,
    paramsType: [DataType.I32, DataType.I32, DataType.I32, DataType.External, DataType.I32],
    paramsValue: [socket._handle.fd, level, option, pointer[0], 4],
    errno: true // set errno as true
  })
// The above code will return a object include three fields include errnoCode, errnoMessage, and the foreign function return value
  // { errnoCode: 22, errnoMessage: 'Invalid argument (os error 22)', value: -1 }
```

**Comment by hertzg** [comment]
Seems to be working like a charm 👍. Resolved.
