### ISSUE TITLE
[Feature Request] Provide examples for WinAPI if possible

### ISSUE THREAD

**Issue by Psychosynthesis** [zhangyuang/node-ffi-rs#3]
One of the features of ffi was the use of native WinApi functions.

Provide an example of using your implementation with WinAPI functions in the Readme. If there are any restrictions on the OS version, please indicate them.

**Comment by zhangyuang** [comment]
I can't quite understand your needs. ffi don't care dynamic library file internal code.

**Comment by Psychosynthesis** [comment]
@zhangyuang the thing is that original ffi provides the ability to use functions from WinAPI directly without having to compile your DLL, like this:

```
var current = ffi.Library("User32.dll", {
   'MessageBoxA': [ 'int', [ winapi.HWND, winapi.LPCWSTR, winapi.LPCWSTR, winapi.UINT ] ]}
);
current.MessageBoxA(ref.NULL, "sss", "sss", 0);
```
--------------

It would be nice if your project could do this too, but I don’t see an example in the doc, so I suspect that it can’t.

In any case, you have already written a useful thing, thank you. The main thing is to add more return types (especially boolean is missing).

**Comment by zhangyuang** [comment]
Thanks for the info, Currently ffi-rs only provides some common types。I will provide the boolean type as soon as possible。As for WinAPI, it looks a bit complicated, but I'll try to provide it in a later release as well!

**Comment by zhangyuang** [comment]
`ffi-rs` version 1.0.13 supports boolean-typed parameters and return values

**Comment by Psychosynthesis** [comment]
@zhangyuang that great, thank's!

One more question... Is it possible to immediately return std:string without creating an intermediate char array?

**Comment by zhangyuang** [comment]
you can describe your need more specified



发自我的iPhone


------------------ Original ------------------
From: Nick ***@***.***&gt;
Date: Sun,Oct 1,2023 2:35 AM
To: zhangyuang/node-ffi-rs ***@***.***&gt;
Cc: yuuang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] [Feature Request] Provide examples forWinAPI if possible (Issue #3)





 
@zhangyuang that great, thank's!
 
One more question... Is it possible to immediately return std:string without creating an intermediate char array?

**Comment by Psychosynthesis** [comment]
I mean the example from the Readme for the `RetType.String` type.

If we're using `RetType.String` and inside the function we're need copying the `std::string` to a `char *cstr`, but it would be nice to be able to just use a construct simple like this:

```
std::string error = "Error text";
return error;
```

**Comment by zhangyuang** [comment]
The c and c++ code in the readme is just a sample. And in ffi scenarios, the return value and parameters must be of c type not c++。std::string is a c++ type not a c type

**Comment by Psychosynthesis** [comment]
Ok got it
