### ISSUE TITLE
Pass a void pointer to be allocated in a C function

### ISSUE THREAD

**Issue by GedorN** [zhangyuang/node-ffi-rs#34]
I'm trying to use a function in C to pass a pointer, have it allocated and modified in C, and then retrieve this modified pointer in Node.js. However, I'm unable to do it at all. Can you help me?

C function:
```c
extern "C" int32_t alloc_pointer(int32_t **c) {
    *c = (int32_t *)malloc(3 * sizeof(int32_t));
    if (*c == NULL) {
        return -1; 
    }

    (*c)[0] = 1;
    (*c)[1] = 2;
    (*c)[2] = 3;

    return 0;
}
```

Node example: 
```js
 let ret = createPointer({
    paramsType: [DataType.I32Array],
    paramsValue: [[]]
  })


  const v = load({
    library: "libsum",
    funcName: 'alloc_pointer', 
    retType: DataType.I32,
    paramsType: [DataType.External],
    paramsValue: ret
  });

  const unwrapPtr = restorePointer({
    paramsValue: ret,
    retType: [DataType.I32Array],
  })
```

**Comment by zhangyuang** [comment]
try with this code

```js
const i32Ptr = createPointer({
    paramsType: [DataType.I32Array],
    paramsValue: [[-1, -1, -1]]
  })[0]

  const v = load({
    library: "libsum",
    funcName: 'alloc_pointer',
    retType: DataType.I32,
    paramsType: [DataType.External],
    paramsValue: [i32Ptr]
  });
  const unwrapPtr = restorePointer({
    paramsValue: [i32Ptr],
    retType: [arrayConstructor({
      type: DataType.I32Array,
      length: 3
    })],
  })
  console.log('111', unwrapPtr)
```

**Comment by GedorN** [comment]
It worked! But do I need to know the size of the array that was allocated to use restorePointer? I will need to work with Buffer and won't know what size it will be allocated.

**Comment by zhangyuang** [comment]
There's no good way if you don't know the length of array, because restore array data by offset pointer is unsafe, we must guarantee the address to which the pointer point is valid.

I will also think whether there has other way to implement this feature

**Comment by zhangyuang** [comment]
An interim solution is create a big  and fixed length space to store the return data

**Comment by GedorN** [comment]
I really appreciate the help.
