### ISSUE TITLE
相同的dll在不同的js掉用就出错

### ISSUE THREAD

**Issue by alancaven** [zhangyuang/node-ffi-rs#35]
![QQ截图20240514021159](https://github.com/zhangyuang/node-ffi-rs/assets/36393563/57fe2469-a5ff-4e8d-9f40-ba0f24417da4)
![QQ截图20240514021129](https://github.com/zhangyuang/node-ffi-rs/assets/36393563/19a39615-02ee-4127-bf0c-7dd2d6e154ab)
如上图所示

**Comment by zhangyuang** [comment]
这个库是用在node.js环境的，看起来你是前端项目
