### ISSUE TITLE
在win2019上运行出现错误

### ISSUE THREAD

**Issue by weziye** [zhangyuang/node-ffi-rs#36]
C:\Users\Administrator\Desktop\test\node_modules\ffi-rs\index.js:309
    throw loadError
    ^

Error: The specified module could not be found.
\\?\C:\Users\Administrator\Desktop\test\node_modules\@yuuang\ffi-rs-win32-x64-msvc\ffi-rs.win32-x64-msvc.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1464:18)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)

**Comment by weziye** [comment]
Node Version: v21.7.1
Operating System Platform: win32
Processor Architecture: x64
OS Type: Windows_NT
OS Version: Windows Server 2019 Standard
OS Release: 10.0.17763
Total Memory: 63.99 GB
Free Memory: 59.71 GB
System Uptime: 674764.421 seconds
Hostname: SYNERGY-E7SASIR
Network Interfaces: {
  'Ethernet 2': [
    {
      address: 'fe80::450b:e544:d337:89df',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '68:b5:99:bd:cb:20',
      internal: false,
      cidr: 'fe80::450b:e544:d337:89df/64',
      scopeid: 9
    },
    {
      address: '104.192.3.238',
      netmask: '255.255.255.252',
      family: 'IPv4',
      mac: '68:b5:99:bd:cb:20',
      internal: false,
      cidr: '104.192.3.238/30'
    }
  ],
  'Loopback Pseudo-Interface 1': [
    {
      address: '::1',
      netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '::1/128',
      scopeid: 0
    },
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 'IPv4',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    }
  ]
}
CPU Information: [
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: {
      user: 3383796,
      nice: 0,
      sys: 784687,
      idle: 670595953,
      irq: 31156
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 1466031, nice: 0, sys: 461796, idle: 672836046, irq: 4437 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 171062, nice: 0, sys: 87656, idle: 674505156, irq: 1671 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 78796, nice: 0, sys: 42406, idle: 674642671, irq: 656 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 67390, nice: 0, sys: 29781, idle: 674666703, irq: 328 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 38328, nice: 0, sys: 19421, idle: 674706125, irq: 171 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 32968, nice: 0, sys: 17250, idle: 674713656, irq: 234 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 20750, nice: 0, sys: 10609, idle: 674732515, irq: 31 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 20281, nice: 0, sys: 10437, idle: 674733140, irq: 203 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 14796, nice: 0, sys: 6843, idle: 674742218, irq: 125 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 14750, nice: 0, sys: 7734, idle: 674741375, irq: 1546 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 11140, nice: 0, sys: 12046, idle: 674740671, irq: 62 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: {
      user: 2692640,
      nice: 0,
      sys: 1941390,
      idle: 670129828,
      irq: 10765
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: {
      user: 1946593,
      nice: 0,
      sys: 1334125,
      idle: 671483140,
      irq: 6171
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 183609, nice: 0, sys: 77281, idle: 674502968, irq: 625 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 79718, nice: 0, sys: 34312, idle: 674649812, irq: 468 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 92000, nice: 0, sys: 29921, idle: 674641921, irq: 234 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 39406, nice: 0, sys: 16781, idle: 674707656, irq: 312 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 50937, nice: 0, sys: 22812, idle: 674690093, irq: 203 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 30812, nice: 0, sys: 13000, idle: 674720031, irq: 171 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 30406, nice: 0, sys: 13156, idle: 674720281, irq: 109 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 22640, nice: 0, sys: 11421, idle: 674729781, irq: 78 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 29421, nice: 0, sys: 12078, idle: 674722328, irq: 171 }
  },
  {
    model: 'Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz',
    speed: 2667,
    times: { user: 17375, nice: 0, sys: 10531, idle: 674735921, irq: 62 }
  }
]

**Comment by zhangyuang** [comment]
可以ls node_modules/@yuuang文件夹看看下面的依赖

**Comment by weziye** [comment]
![WX20240515-161145@2x](https://github.com/zhangyuang/node-ffi-rs/assets/23327245/b52db8f3-0d39-43dd-8359-1da3c9720c09)

**Comment by zhangyuang** [comment]
看起来是调用ffi-rs时候的错误，提供一下调用代码

**Comment by weziye** [comment]
相同的代码可以运行在win10上运行
Operating System Platform: win32
Processor Architecture: x64     
OS Type: Windows_NT
OS Version: Windows 10 Pro      
OS Release: 10.0.18363
Total Memory: 4.00 GB
Free Memory: 1.14 GB
System Uptime: 126.437 seconds  
Hostname: DESKTOP-DR9AMH4



<img width="725" alt="image" src="https://github.com/zhangyuang/node-ffi-rs/assets/23327245/752e1404-22a3-46f0-be9a-b28125b7bd77">

**Comment by zhangyuang** [comment]
直接使用require('@yuuang/ffi-rs-win32-x64-msvc').open试试

**Comment by weziye** [comment]
不行的，在下面这个地方报错了
<img width="668" alt="image" src="https://github.com/zhangyuang/node-ffi-rs/assets/23327245/f00e58c5-bb91-4438-a0b0-7340970bce38">

**Comment by weziye** [comment]
是的

**Comment by zhangyuang** [comment]
报什么错误再具体贴一下, 类似于这样的输出信息
<img width="659" alt="image" src="https://github.com/zhangyuang/node-ffi-rs/assets/17424434/54f47bcf-175d-48d9-98d6-5e7abd4d2ef4">

**Comment by weziye** [comment]
直接上服务器看吧，报错信息就那么一点点
<img width="272" alt="image" src="https://github.com/zhangyuang/node-ffi-rs/assets/23327245/fae776b3-e428-4f58-b894-2dab215f83a3">

**Comment by zhangyuang** [comment]
ssh的端口是多少

**Comment by weziye** [comment]
3389 这是桌面的，需要用Remote desktop

**Comment by zhangyuang** [comment]
你直接加我微信吧 yuuangC

**Comment by zhangyuang** [comment]
已解决
