### ISSUE TITLE
Is it possible to add error output when the return value types do not match?

### ISSUE THREAD

**Issue by Psychosynthesis** [zhangyuang/node-ffi-rs#4]
I've encountered that if I specify an invalid return type for a function, the function itself executes, however, when the function returns, node crashes without any errors...

But i not quite sure, may be there is some problem with RetType.String...

Minimal code to reproduce:

```
// test.cpp, compile with: g++ -shared -o test.dll test.cpp
const char *EXAMPLE_ERR = "Example error";
extern "C" const char *setVolume(double newVolume) {
    std::cout << EXAMPLE_ERR << std::endl; // This work, we will see the error
    return EXAMPLE_ERR; // Here is node fall...
    
    // i also try standart way like
    // char* ret = new char[strlen(EXAMPLE_ERR ) + 1];
    // strcpy(ret, EXAMPLE_ERR );
    // return ret;
    // This also does not work...
}
```
I tried few return types, for example `extern "C" char *setVolume()` and so on...

```
// test.js
const { load, RetType, ParamsType } = require('ffi-rs');

const useDll = (vol) => {
  load({
    library: './test.dll', // path to the dynamic library file
    funcName: 'setVolume', // the name of the function to call
    retType: RetType.String, // the return value type
    paramsType: [ParamsType.Double], // the parameter types
    paramsValue: [vol] // the actual parameter values
  });
}
useDll(0.9); // here node was fall
console.log('Test'); // We didn't see this
```

The problem is that the function code runs, but it crashes without any messages at the time of return, so it’s difficult to quickly understand what the error is...

And by the way, I don’t understand why this doesn’t work, does the function seem to return the same type as in the example with concatenateStrings?

And i want to say is look like there is some problem to publishing last version of NPM-package. I see that this is must be done with github actions, but where is some error there.

**Comment by zhangyuang** [comment]
Perfect error tips is the next thing todo

**Comment by Psychosynthesis** [comment]
@zhangyuang ok, but what's wrong with my example? Can you reproduce that problem?

**Comment by zhangyuang** [comment]
In the libffi scenario, you have to copy the string memory into a readable memory area using strcpy, if you use EXAMPLE_ERR directly it's a pointer to a string constant that points to a read-only memory

```
extern "C" const char *setVolume(double newVolume) {
  char *cstr = new char[100];
  strcpy(cstr, EXAMPLE_ERR);
  return cstr; // Here is node fall...
}

```

**Comment by Psychosynthesis** [comment]
@zhangyuang as I mentioned in the first post - I tried this way. This causes node fall.

I also used the `concatenateStrings ` function from examples - it also breaks node.

load({
  library: dynamicLib,
  funcName: 'concatenateStrings',
  retType: RetType.String,
  paramsType: [ParamsType.String, ParamsType.String],
  paramsValue: [c, d]
})

My NodeJS version is 16.20.2, system win 7 x64

**Comment by zhangyuang** [comment]
🤔️ I can't reproduce, concatenateStrings function can be executed succeed in my environment(macos node16/18) and github actions

**Comment by Psychosynthesis** [comment]
@zhangyuang ok, i will check my code again

**Comment by Psychosynthesis** [comment]
Well, I checked, concatenateStrings throws an error in my environment...
Without messages it is impossible to understand why. I'll wait for the implementation of error output.

**Comment by sinisterdev** [comment]
me and a co-worker ran the same exact code, he gets no error on mac while I do on windows, that might be why.
waiting for error output too

**Comment by sinisterdev** [comment]
While the application runs fine on mac, when I try running it on windows node just dies without outputting any errors.

We are using basically this:
https://github.com/bogdanfinn/tls-client/blob/master/cffi_dist/example_node/index.js

and adapted node-ffi-rs instead of ffi-napi since it's slower.

On mac it works fine, in windows It just dies without receiving the return value

**Comment by zhangyuang** [comment]
Can you provide your arch? In `ffi-rs` github actions, the test can be executed succeed in x86_64-pc-windows-msvc

**Comment by zhangyuang** [comment]
In my experience, this may be due to the fact that the length of the array passed in when using a string array exceeds the original length of the array causing the program to exit abnormally
