### ISSUE TITLE
Startup error in vite environment

### ISSUE THREAD

**Issue by dreamOf** [zhangyuang/node-ffi-rs#42]
## Current ffi-rs version: 

{
  "name": "ffi-rs",
  "version": "1.0.78",
  "main": "index.js",
  "types": "index.d.ts",
  "description": "A module written in Rust and N-API provides interface (FFI) features for Node.js",
  "napi": {
    "name": "ffi-rs",
    "triples": {
      "additional": [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "aarch64-unknown-linux-musl",
        "i686-pc-windows-msvc",
        "x86_64-unknown-linux-musl",
        "aarch64-pc-windows-msvc"
      ]
    }
  },
  "author": "zhangyuang",
  "homepage": "https://github.com/zhangyuang/node-ffi-rs#readme",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zhangyuang/node-ffi-rs.git"
  },
  "keywords": [
    "ffi",
    "rust",
    "node.js",
    "napi"
  ],
  "files": [
    "index.js",
    "index.d.ts",
    "README.md"
  ],
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "@napi-rs/cli": "^2.15.2",
    "@types/node": "^20.8.7",
    "benny": "^3.7.1",
    "conventional-changelog-cli": "^4.1.0",
    "esno": "^4.0.0",
    "ffi-napi": "^4.0.3",
    "koa": "^2.14.2",
    "shelljs": "^0.8.5",
    "typescript": "^5.4.5"
  },
  "scripts": {
    "artifacts": "napi artifacts",
    "build:c": "node scripts/compile.js",
    "build:dev": "env=development node scripts/build.js",
    "build": "node scripts/build.js",
    "publish:npm": "node scripts/publish.js",
    "test": "esno ./test.ts",
    "changelog": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add . && git commit -m \"docs: update changelog.md\" && git push origin master",   
    "pub": "npm version patch && git push origin master --tags && npm run changelog",
    "pub:alpha": "npm version prerelease --preid=alpha && git push origin master --tags"
  },
  "optionalDependencies": {
    "@yuuang/ffi-rs-darwin-arm64": "1.0.78",
    "@yuuang/ffi-rs-darwin-x64": "1.0.78",
    "@yuuang/ffi-rs-linux-arm64-gnu": "1.0.78",
    "@yuuang/ffi-rs-linux-arm64-musl": "1.0.78",
    "@yuuang/ffi-rs-linux-x64-gnu": "1.0.78",
    "@yuuang/ffi-rs-linux-x64-musl": "1.0.78",
    "@yuuang/ffi-rs-win32-arm64-msvc": "1.0.78",
    "@yuuang/ffi-rs-win32-ia32-msvc": "1.0.78",
    "@yuuang/ffi-rs-win32-x64-msvc": "1.0.78"
  }
}

$ ls node_modules/@yuuang

    目录: E:\test\my-vue-app\node_modules\@yuuang

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          2024/6/5     16:05                ffi-rs-win32-ia32-msvc
d-----          2024/6/5     16:05                ffi-rs-win32-x64-msvc

Print current Node.js info with the following code

x64 win32

## Descibe your problem in detail
const { load, DataType, open, close, arrayConstructor } = require('ffi-rs')
When I use this line of code in a project, an exception occurs when starting the project, and the error message is as follows:

  VITE v5.2.12  ready in 445 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
X [ERROR] No loader is configured for ".node" files: node_modules/@yuuang/ffi-rs-win32-ia32-msvc/ffi-rs.win32-ia32-msvc.node

    node_modules/ffi-rs/index.js:80:36:
      80 │             nativeBinding = require('@yuuang/ffi-rs-win32-ia32-msvc')
         ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] No loader is configured for ".node" files: node_modules/@yuuang/ffi-rs-win32-x64-msvc/ffi-rs.win32-x64-msvc.node

    node_modules/ffi-rs/index.js:66:36:
      66 │             nativeBinding = require('@yuuang/ffi-rs-win32-x64-msvc')
         ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Please take a look at it, experts. Thank you！

**Comment by dreamOf** [comment]
I am using FFI-RS, and this is my package.json file:{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "ffi-rs": "^1.0.78",
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "vite": "^5.2.0"
  }
}

**Comment by dreamOf** [comment]
Am I using the wrong method?
<script setup>
import HelloWorld from './components/HelloWorld.vue'
const { load, DataType, open, close, arrayConstructor } = require('ffi-rs')
</script>

**Comment by zhangyuang** [comment]
The Vue component will be transformed by Vite and executed in the browser. Maybe you should learn basic knowledge about  Node.js and bundler
