### ISSUE TITLE
Error: 找不到指定的模块。 (os error 126)

### ISSUE THREAD

**Issue by Hyliuz** [zhangyuang/node-ffi-rs#43]
## Current ffi-rs version
ffi-rs : 1.0.78
Print current Node.js info with the following code
  "dependencies": {
    "days": "^1.10.7",
    "ee-core": "^2.9.2",
    "electron-updater": "^5.3.0",
    "ffi-rs": "^1.0.78",
    "lodash": "^4.17.21"
  }
## Current Node.js arch

Print current Node.js info with the following code

x64 win32

## Descibe your problem in detail
Ipc.vue:27 Uncaught (in promise) Error: 找不到指定的模块。 (os error 126)
    at Ipc.vue:27:7
这是我使用ffi-rs open 方法出现的，在ffi-napi 中调用没有问题
  ipc.invoke(ipcApiRoute.getDllPath)
    .then((res) => {
      let dirPath = path.join(res, "pohotoSDK", "bin");
      const lib4 = path.join(dirPath, "pohotoSysSDKENCRYPT.dll");
      console.log(lib4)
      open({
        library: 'libsum', // key
        path: lib4 // path
      })
      const r = load({
        library: 'libsum', // path to the dynamic library file
        funcName: 'sys_exampleinit', // the name of the function to call
        retType: DataType.I32, // the return value type
        paramsType: [], // the parameter types
        paramsValue: [] // the actual parameter values
      })
    })
## What's your expected result
这是什么问题导致的？

**Comment by zhangyuang** [comment]
提供完整的错误信息日志

**Comment by zhangyuang** [comment]
确定路径没有问题的话大概率是动态链接文件的运行环境系统架构与构建环境系统架构不同

**Comment by neko-para** [comment]
如果dll所在路径不在PATH中的话，由于Windows逻辑限制，需要先调用`SetDefaultDllDirectories`扩展dll查找路径，然后用`AddDllDirectory`将dll所在路径添加到查找列表
简单来说，直接把路径加到PATH里面就能解决问题

**Comment by zhangyuang** [comment]
dlopen方法使用的是第三方库，在windows底层调用的是GetModuleHandleExW，与ffi-napi一致。

**Comment by Hyliuz** [comment]
> dlopen方法使用的是第三方库，在windows底层调用的是GetModuleHandleExW，与ffi-napi一致。

感谢，问题已经解决，如三楼所说原因，我尝试把依赖的一些dll添加到环境变量后，解决
