### ISSUE TITLE
retType  void * 返回定义问题

### ISSUE THREAD

**Issue by Hyliuz** [zhangyuang/node-ffi-rs#46]
## Current ffi-rs version
{
  "name": "ffi-rs",
  "version": "1.0.78",
  "main": "index.js",
  "types": "index.d.ts",
  "description": "A module written in Rust and N-API provides interface (FFI) features for Node.js",
  "napi": {
    "name": "ffi-rs",
    "triples": {
      "additional": [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "aarch64-unknown-linux-musl",
        "i686-pc-windows-msvc",
        "x86_64-unknown-linux-musl",
        "aarch64-pc-windows-msvc"
      ]
    }
  },
  "author": "zhangyuang",
  "homepage": "https://github.com/zhangyuang/node-ffi-rs#readme",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zhangyuang/node-ffi-rs.git"
  },
  "keywords": [
    "ffi",
    "rust",
    "node.js",
    "napi"
  ],
  "files": [
    "index.js",
    "index.d.ts",
    "README.md"
  ],
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "@napi-rs/cli": "^2.15.2",
    "@types/node": "^20.8.7",
    "benny": "^3.7.1",
    "conventional-changelog-cli": "^4.1.0",
    "esno": "^4.0.0",
    "ffi-napi": "^4.0.3",
    "koa": "^2.14.2",
    "shelljs": "^0.8.5",
    "typescript": "^5.4.5"
  },
  "scripts": {
    "artifacts": "napi artifacts",
    "build:c": "node scripts/compile.js",
    "build:dev": "env=development node scripts/build.js",
    "build": "node scripts/build.js",
    "publish:npm": "node scripts/publish.js",
    "test": "esno ./test.ts",
    "changelog": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add . && git commit -m \"docs: update changelog.md\" && git push origin master",
    "pub": "npm version patch && git push origin master --tags && npm run changelog",
    "pub:alpha": "npm version prerelease --preid=alpha && git push origin master --tags"
  },
  "optionalDependencies": {
    "@yuuang/ffi-rs-darwin-arm64": "1.0.78",
    "@yuuang/ffi-rs-darwin-x64": "1.0.78",
    "@yuuang/ffi-rs-linux-arm64-gnu": "1.0.78",
    "@yuuang/ffi-rs-linux-arm64-musl": "1.0.78",
    "@yuuang/ffi-rs-linux-x64-gnu": "1.0.78",
    "@yuuang/ffi-rs-linux-x64-musl": "1.0.78",
    "@yuuang/ffi-rs-win32-arm64-msvc": "1.0.78",
    "@yuuang/ffi-rs-win32-ia32-msvc": "1.0.78",
    "@yuuang/ffi-rs-win32-x64-msvc": "1.0.78"
  }
}

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            2024/6/7    10:47                ffi-rs-win32-ia32-msvc
d----            2024/6/7    10:47                ffi-rs-win32-x64-msvc

## Current Node.js arch
x64 win32
## Descibe your problem in detail
     open({
        library: 'kernel32',
        path: 'kernel32.dll'
      })
   const dllPath = unwrapPointer(createPointer({
        paramsType: [DataType.String],
        paramsValue: ['path://xxxxxxxx']
      }))
    const r = load({
        library: 'kernel32',
        funcName: 'AddDllDirectory',
        retType: DataType.External,
        paramsType: [DataType.External],
        paramsValue: [dllPath],
        errno: true
      })
DLL_DIRECTORY_COOKIE WINAPI AddDllDirectory(
    _In_ PCWSTR NewDirectory
 );
typedef PVOID DLL_DIRECTORY_COOKIE, *PDLL_DIRECTORY_COOKIE;
typedef void *PVOID;
typedef _Null_terminated_ CONST WCHAR *LPCWSTR, *PCWSTR;

返回错误Uncaught (in promise) Error: expect External, got: Object
## What's your expect result
文档中说明中，看起来 char * a   可以直接用DataType.String  传入 一个字符串就可以，但是尝试使用这种方式，返回Uncaught (in promise) Error ，也是要和ffi-napi 方式一个创建一个buffer 然后 写入值再传递吗？void * 改如何定义？

**Comment by zhangyuang** [comment]
1、void*是通用类型指针，使用时按需设置需要转换的数据类型
2、使用external和DataType.String在你上面的例子中没有区别
3、dllPath的类型是External[],修改为paramsValue:dllPath,使用ts编写代码以便获取类型提示

**Comment by Hyliuz** [comment]
open({
        library: 'kernel32',
        path: 'kernel32.dll'
      })
      const dllPath = unwrapPointer(createPointer({
        paramsType: [DataType.String],
        paramsValue: ["D:\\dll"]
      }))
      const r = load({
        library: 'kernel32',
        funcName: 'AddDllDirectory',
        retType: DataType.External,
        paramsType: DataType.External,
        paramsValue: dllPath,
        errno: true
      })

修改成这样的话控制台出现Uncaught (in promise) TypeError: params.paramsType?.map is not a function，
同时我也尝试使用
      open({
        library: 'kernel32',
        path: 'kernel32.dll'
      })
      const r = load({
        library: 'kernel32',
        funcName: 'AddDllDirectory',
        retType: DataType.Void,
        paramsType: [DataType.String],
        paramsValue: ["D:\\dll"],
        errno: true
      })
返回错误{errnoCode: 87, errnoMessage: '参数错误。 (os error 87)', value: undefined} 目前不清楚问题在哪里

**Comment by zhangyuang** [comment]
AddDllDirectory接受的类型是wchar*而不是char*，目前ffi-rs还未支持wchar*的参数类型，我将会在下一个版本支持

**Comment by zhangyuang** [comment]
1.0.79新增DataType.WString可以试试
