### ISSUE TITLE
请问一下 我是用C++回调js函数时 使用的是这样的方法 但是回调函数直接卡住

### ISSUE THREAD

**Issue by a702169588** [zhangyuang/node-ffi-rs#48]
js调度代码:
在electron中使用的
let getEvent = (eventName, msg, x, y) => {
  console.log(eventName, msg, x, y)
}
let isPrevent = false
this.b = load({
        library: 'libkeyboardHook', // path to the dynamic library file
        funcName: 'setParams', // the name of the function to call
        retType: DataType.Void, // the return value type
        paramsType: [
          DataType.Boolean,
          funcConstructor({
            paramsType: [DataType.String, DataType.I32, DataType.I32, DataType.I32],
            retType: DataType.Void
          })
        ],
        paramsValue: [isPrevent, getEvent]
      })

C++代码
typedef void(__cdecl *GetEventFunc)(char *, int, int, int);
LIB_H void setParams(bool isPrevent, GetEventFunc callback);

LIB_H void setParams(bool isPrevent, GetEventFunc callback)
{
	g_isPrevent = isPrevent;
	g_callback = callback;
	callback（“123”, 1, 1, 1331);
	return;
}

经排查应该是第一个参数有问题导致的 应该要怎么传参 才能正常把string传出来呢

**Comment by zhangyuang** [comment]
没有看懂你的问题以及错误信息，请提供完整的可复现仓库

**Comment by a702169588** [comment]
问题就是在C++ 调度callback回来到 getEvent时 调度不了 直接卡死了

**Comment by zhangyuang** [comment]
funcConstructor设置freeCFuncParamsMemory为false试试

**Comment by a702169588** [comment]
正常了 谢谢

**Comment by a702169588** [comment]
那这样配置 后续的资源释放会有问题吗

**Comment by zhangyuang** [comment]
需要手动释放，既然默认为true在你的库场景会报错，那说明你的库会自己管理这块资源的内存

**Comment by zhangyuang** [comment]
介于多个用户反馈dynamic library会自行管理内存，ffi-rs >= 1.0.80 将会默认设置`freeCFuncParamsMemory ` 以及 `freeResultMemory` 为false

**Comment by a702169588** [comment]
是一个char*的常量来的 C++那边应该也不需要处理把？
