### ISSUE TITLE
com组件动态库可以调用吗？

### ISSUE THREAD

**Issue by dreamOf** [zhangyuang/node-ffi-rs#49]
![1718265268223](https://github.com/zhangyuang/node-ffi-rs/assets/21993019/9cab3d6d-e2ab-458c-b2cd-74df8ba55a13)
请问这种动态库可以调用吗？

**Comment by zhangyuang** [comment]
ffi只能在纯c数据类型下调用，不支持c++的std::string，需要包一层char*类型的函数签名

**Comment by dreamOf** [comment]
我小白一个，我有动态库dll文件，可不可帮忙封装下，有偿服务。

**Comment by zhangyuang** [comment]
你可以寻找这个组件库的提供方封装

**Comment by dreamOf** [comment]
组件方不提供，只能自己封装。不管怎样，还是谢谢大佬的指导。
