### ISSUE TITLE
调用 user32 方法失败，哪儿没对呢？

### ISSUE THREAD

**Issue by waitingsong** [zhangyuang/node-ffi-rs#50]
## Current ffi-rs version

`1.0.80`

## Current Node.js arch

x64 win32
nodejs 22.1.0

## Descibe your problem in detail
```ts
import { resolve } from 'node:path'
import { DataType, open, load } from 'ffi-rs'

     const path = resolve('c:/Windows/System32/user32.dll')
      open({
        library: 'user32',
        path: path,
      })
      const hWnd = load({
        library: "user32",
        funcName: "FindWindowExW",
        retType: DataType.I32,
        paramsType: [DataType.I32, DataType.I32, DataType.WString, DataType.WString],
        paramsValue: [0, 0, 'Notepad', ''],
      })
      // const hWnd = await user32FindWindowEx(0, 0, calcLpszNotepad, null)
      void hWnd 
```

## What's your expect result
hWnd 正确赋值

## 实际结果

```
thread '<unnamed>' panicked at src\lib.rs:194:6:
called `Result::unwrap()` on an `Err` value: Error { status: Unknown, reason: "Cannot find \"user32FindWindowEx\" function in shared library", maybe_raw: 0x0 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by waitingsong** [comment]
calcLpszNotepad 值改成 `Buffer.from('Notepad\n', 'ucs2')` 也不行

**Comment by zhangyuang** [comment]
错误原因提示的很明显，没有user32FindWindowEx方法

**Comment by waitingsong** [comment]
> 错误原因提示的很明显，没有user32FindWindowEx方法

是的，发现了。修改后执行成功。
不过获取 计算器 应用失败， 使用 ‘Notepad' 或者 ”计算器“，hwnd ==0

**Comment by zhangyuang** [comment]
返回的结果是0说明调用成功了

**Comment by waitingsong** [comment]
哦哦。

另外请教下， 对于 `uint32*`,  `uint64*`  以及 `uint32**` 之类的指针，应该响应使用哪个 `DataType` 定义呢？
全部都用 `DataType.External` 么

**Comment by zhangyuang** [comment]
DataType.External代表指针，至于这个指针是单重指针还是多重指针DataType.External并不关心。需要自行保证指针类型的正确性

**Comment by waitingsong** [comment]
> 返回的结果是0说明调用成功了

按照 [文档](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindowexw) ，如果查找到窗口，返回值是非空（>0），如果要获取”计算器“的窗口，应该传入什么值呢。 以前用 node-ffi 的时候，传入 Buffer('Calculator\0', 'ucs2') 就能成功。

**Comment by zhangyuang** [comment]
DataType改为`arrayConstructor({
    type: DataType.U8Array,
    length: buffer.length
  })`试试

**Comment by waitingsong** [comment]
```ts
const buf = Buffer.from('Calculator\0', 'ucs2')
const buf2 = Buffer.from('\0', 'ucs2')
const hwnd = await load({
  library: "user32",
  runInNewThread: true,
  funcName: 'FindWindowExW',
  retType: DataType.I32,
  paramsType: [
    DataType.I32,
    DataType.I32,
    arrayConstructor({ type: DataType.U8Array, length: buf.length }),
    arrayConstructor({ type: DataType.U8Array, length: buf2.length }),
  ],
  paramsValue: [0, 0, buf, buf2],
})
console.log(hwnd)
```

这样，走到 `await load` 的时候直接退出，任何异常信息都没有。

**Comment by waitingsong** [comment]
```ts
const hwnd = await load({
  library: "user32",
  runInNewThread: true,
  funcName: 'FindWindowExW',
  retType: arrayConstructor({ type: DataType.U8Array, length: 8 }),
  paramsType: [DataType.I32, DataType.I32, DataType.WString , DataType.WString],
  paramsValue: [0, 0, 'Calculator', ''],
})
console.log(hwnd)
```
异常信息： "Segmentation fault"

**Comment by zhangyuang** [comment]
...参数类型改为U8Array代表buffer

**Comment by waitingsong** [comment]
这样倒是可以执行 
```ts
const hwnd = await load({
  library: "user32",
  runInNewThread: true,
  funcName: 'FindWindowExW',
  retType: DataType.External,  // <---------
  paramsType: [DataType.I32, DataType.I32, DataType.WString, DataType.WString],
  paramsValue: [0, 0, 'Calculator', ''],
})
```
打印 `[External: 1ebe8e99110]` 之类的信息
不过不知道结果是否正常。

**Comment by zhangyuang** [comment]
你的返回类型是指针当然看不到信息，返回结果保持DataType.I32不变，参数你要传buffer就用u8array，你要传string就用string/wstring

**Comment by waitingsong** [comment]
retType 设置为 DataType.I32, 结果都是 0。 相同参数用在以前的 node-fii 就能反正正确值。
这是哪儿不对呢……

**Comment by zhangyuang** [comment]
HWND是指针类型的话你就用DataType.external承接，然后传入别的函数继续用DataType.external作为参数类型透传

**Comment by waitingsong** [comment]
HWND 通常是整数吧
DataType.external 是个对象，我怎么判断执行成功与否呢？

**Comment by zhangyuang** [comment]
你期望得到整数结果就用i32作为返回类型，你期望得到指针结果就用external作为返回类型。ffi不关心具体逻辑细节。怎么判断执行成功与否看这个函数的介绍，这同样不是ffi本身关心的问题。

**Comment by waitingsong** [comment]
```ts
const hwnd = FindWindowEx(0, 0, 'Notepad', '无标题 - 记事本')
```
这个代码用 ffi-rs 来执行，retType 是 int32 时，返回是 0 （表示未找到窗口句柄），换成 koffi 执行就是正常的大于0的整数。
如果 retType 设置为指针类型，那么无论传入的参数是否正确， ffi-rs 都会返回一个真对象（无法判断是否找到窗口），而 koffi 如果参数不正确返回的是 null（可以判断没找到窗口）。

**Comment by zhangyuang** [comment]
你先搞清楚什么是逻辑错误什么是调用错误。只要这次调用没有segment fault就说明这次调用是成功的，业务层面的错误是由具体的方法来决定如何表现。就如同http状态是200但是错误信息由errmsg来返回。你可以调用的时候设置errno:true来查看errno信息，前提是这个动态库设置了errno错误信息

**Comment by waitingsong** [comment]
要不你看看 [FindWindowExW](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindowexw) 接口文档，返回值 `HWND` 的定义
```ts
const hwnd = FindWindowExW(0, 0, 'Notepad', '无标题 - 记事本')
```
这个调用正常是能找到已经打开的记事本窗口，返回值 hwnd 为非零正整数。然而使用 ffi-rs 来执行结果就是 0。 能不能解释下原因呢？

**Comment by hecan1994** [comment]
> 这样倒是可以执行
> 
> ```ts
> const hwnd = await load({
>   library: "user32",
>   runInNewThread: true,
>   funcName: 'FindWindowExW',
>   retType: DataType.External,  // <---------
>   paramsType: [DataType.I32, DataType.I32, DataType.WString, DataType.WString],
>   paramsValue: [0, 0, 'Calculator', ''],
> })
> ```
> 
> 打印 `[External: 1ebe8e99110]` 之类的信息 不过不知道结果是否正常。

我看了FindWindowExW的函数说明,最后一个参数为nullptr的时候才是不限定名称的,NULL和空字符串还是不一样的，我尝试了一下传入""似乎找不到。
要传NULL的话就相当于传一个等于0的指针，这个时候需要把最后一个paramsType改成I64（对于64位机），这样就能找到了，如果returnType是I64的话，应该是一个非0值(相当于指针地址直接当做数字)，而传空字符串时则是0。如果返回值设为External,我推测是打印出来的东西可能是库内部创建的C指针的指针，应该总是不为0。
如何确定获取的HWnd对不对呢，我就又去找了一个函数GetWindowTextA [https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowtexta](url)，没选GetWindowTextW(宽字符版)是因为node并不自带gbk编码，windows下的中文总是要麻烦那么一点，我又因为电脑node版本问题搞不定npm i iconv,我就直接复制结果用python翻了。
代码如下供参考
```javascript
const { resolve } = require('node:path')
const { DataType, open, load } = require("ffi-rs")

const path = resolve('c:/Windows/System32/user32.dll')
open({
    library: 'user32',
    path: path,
})
const hWnd = load({
    library: "user32",
    funcName: "FindWindowExW",
    retType: DataType.External,
    paramsType: [DataType.I32, DataType.I32, DataType.WString, DataType.I64],
    paramsValue: [0, 0, 'Notepad', 0/*'无标题 - 记事本'*/],
})

console.log(hWnd)

const resBuffer = Buffer.alloc(40, 0)
const w = load({
    library: "user32",
    funcName: "GetWindowTextA",
    retType: DataType.I32,
    paramsType:[DataType.External, DataType.U8Array, DataType.I32],
    paramsValue: [hWnd, resBuffer, 100],
})
console.log(resBuffer)
```
我新打开一个记事本的时候结果为
`<Buffer ce de b1 ea cc e2 20 2d 20 bc c7 ca c2 b1 be 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>`
然后扔到python里
```python shell
>>> bytes([0xce,0xde,0xb1,0xea,0xcc,0xe2,0x20,0x2d,0x20,0xbc,0xc7,0xca,0xc2,0xb1,0xbe]).decode('gbk')
'无标题 - 记事本'
```

**Comment by zhangyuang** [comment]
完善的回复👍，External代表一个包含指针地址的原生对象。总之总结就是ffi-rs不关心逻辑问题，开发者需要自己弄清楚在当前动态库的函数调用过程中期望参数类型和返回类型以及如何进行正确逻辑的校验
