### ISSUE TITLE
函数调用错误。

### ISSUE THREAD

**Issue by dreamOf** [zhangyuang/node-ffi-rs#53]
错误信息如下：
![1718885003970](https://github.com/zhangyuang/node-ffi-rs/assets/21993019/2a8d637d-c6b1-465e-b3f2-1ff6809e6d1c)
函数名字是：char* __stdcall NationEcTrans(char* strUrl,char* InData,char* OutData)
调用代码；
    const dynamicLib=path.resolve(__dirname,'NationECCode.dll')
    open({
        library: 'lib', // key
        path: dynamicLib // path
    })
    const url = "https://此处替换成中台地址/localcfc/api/hsecfc/localQrCodeQuery"
    const InData = {"data":{"businessType":"01101","deviceType":"","officeId":"32760","officeName":"123","operatorId":"test001","operatorName":"456",
            "orgId":"35020319001"},"orgId":"35020319001","transType":"ec.query"}
    const outData=""
    const r = load({
        library: "lib", // path to the dynamic library file
        funcName: 'NationEcTrans', // the name of the function to call
        retType: DataType.String, // the return value type
        paramsType: [DataType.String, DataType.String, DataType.String], // the parameter types
        paramsValue: [url, InData,outData] // the actual parameter values
        // freeResultMemory: true, // whether or not need to free the result of return value memory automatically, default is true
    })

    console.log("----"+r)

请问下是参数传递问题吗？

**Comment by zhangyuang** [comment]
使用最新版本ffi-rs试试或者freeresultmemory设置为false试试

**Comment by dreamOf** [comment]
试过了，不能解决这个错误

**Comment by zhangyuang** [comment]
InData没有stringify？

**Comment by dreamOf** [comment]
可以了，谢谢大佬。
