### ISSUE TITLE
Potential buffer overrun for fixed-length U8Array

### ISSUE THREAD

**Issue by hecan1994** [zhangyuang/node-ffi-rs#55]
## Current ffi-rs version
v1.0.83
```
d-----         2024/6/24     17:21                ffi-rs-win32-ia32-msvc
d-----         2024/6/24     17:21                ffi-rs-win32-x64-msvc
```
## Current Node.js arch

x64 win32

## Descibe your problem in detail

```C++  dllmain.cpp
#include <iostream>

template <size_t L>
void PrintCstring(const char (&a)[L])
{
    for (auto c: a)
    {
        std::cout << int(c) << " ";
    }
    std::cout << std::endl;
}

extern "C" {
    typedef struct {
        int x;
        double b;
        char s[10];
        char s2[23];
    } Stu;

    void CallStruct2(Stu *s) {
        PrintCstring(s->s);
        PrintCstring(s->s2);
        s->x += 3;
        s->b += 7.5;
        s->s[3] = 'B';
        s->s2[5] = 'X';
        std::cout 
        << "x = " << s->x  
        << " b = " << s->b 
        << " s = " << s->s 
        << " s2 = " << s->s2
        << std::endl;
    }
} // extern "C"
```
compiled to test.dll by mingw gcc13
`g++ dllmain.cpp -o test.dll --shared --std=c++17`

call by javascript code with ffi-rs
```javascript main.js
const {load, open, DataType, createPointer, restorePointer, arrayConstructor, unwrapPointer, funcConstructor } = require("ffi-rs")

const dllPath = "test.dll"
open({ library: 'libtest', path: dllPath, });

const CharArrayType = (len) => {
    return arrayConstructor({
        type: DataType.U8Array,
        length: len,
        dynamicArray: false
    })
}

const StructType = {
    x: DataType.I32,
    b: DataType.Double,
    s: CharArrayType(10),
    s2: CharArrayType(23),
}

let s = {x: 332, b: 9.97, s: Buffer.from("abcdef"), s2: Buffer.from("baaaaaaaaaaaa")};

let sp = createPointer({
    paramsType: [StructType,],
    paramsValue: [s,]
})

load({
    library: "libtest",
    funcName: "CallStruct2",
    retType: DataType.Void,
    paramsType: [DataType.External,],
    paramsValue: [unwrapPointer(sp)[0],],
})

let restoredata = restorePointer({
    retType: [StructType,],
    paramsValue: sp,
})

console.log(restoredata)
```

## What's your expect result

The result of  `restoredata` is 
```
[
  {
    x: 335,
    b: 17.47,
    s: <Buffer 61 62 63 42 65 66 00 00 62 61>,
    s2: <Buffer 62 61 61 61 61 58 61 61 61 61 61 61 61 00 00 00 00 00 00 00 00 00 00>
  }
]
```
There is a non-zero "62, 61" tail for field s (char[10]). It might be controversial to talk about what result I 'expect' because I acutally didn't pass a 10-length buffer for field s. In the following tests, I found the tail always accorded with s2's header. The reason I add a template function in the code is to locate where the pontential (I thought) overrun happened. The stdout result is 

```
97 98 99 100 101 102 0 0 98 97 
98 97 97 97 97 97 97 97 97 97 97 97 97 0 0 0 0 0 0 0 0 0 0
x = 335 b = 17.47 s = abcBef s2 = baaaaXaaaaaaa
```

It seems that the original char s[10] buffer had been "contaminated" when it comes from javascript to C (which, instead of encountering some memory overlaps when copy the result from C back to javascript). I think the real length(capacity) of `Buffer.from("abcdef")` might be smaller than 10, and by coincidence followed by "Buffer.from('baaa....')", thus their memory was copied . I notice that ffi-rs library has lots of type-checking code, so I think this behavior might be a concern.

I believe this is caused by create_struct.rs, line 147. `buffer.as_ptr()` is copied with `array_len`. The size of the buffer is not checked.
The question is, when user put in a shorter buffer in fixed-length U8Array (which seems ... a bit common?), whether the library should return a buffer with zero-filled tail, or it checks the given buffer length and throw an error?

我是在测试如何调用struct指针时偶然遇到这样的问题，推测Node.js初始化Buffer默认长度可能是8？（因为我用Buffer.from("abcd")或者更短也遇到一样的结果），不过这个问题也可以理解为用户确实填入了不符合的参数所以产生了未定义的行为，但是我觉得用户在处理U8Array也就是C-style string的情况下很大概率会丢一个短于实际长度的Buffer和字符串字面量作为参数，那么ffi-rs库对这种行为是自动帮用户在尾部补0填充满buffer，还是在dynamicArray = false的情况下对buffer长度也做检查以抛异常的方式应对呢

**Comment by zhangyuang** [comment]
因为这两个char[]在内存地址中是连续存储的
第一个char写入的时候以10为长度进行写入,等于写入了不符合预期的内存地址。
使用如下代码测试可以验证js中创建buffer会连续分配内存
```
  const StructType = {
    x: DataType.I32,
    b: DataType.Double,
    s: CharArrayType(10),
    s2: CharArrayType(23),
  }
  const b1 = Buffer.from("abcdef")
  const b2 = Buffer.from("0")
  const b3 = Buffer.from("aa")
  let s = { x: 332, b: 9.97, s: b1, s2: b3 };
  let sp = createPointer({
    paramsType: [StructType,],
    paramsValue: [s,]
  })
  let restoredata = restorePointer({
    retType: [StructType],
    paramsValue: sp,
  })
xxx [
  {
    x: 332,
    b: 9.97,
    s: <Buffer 61 62 63 64 65 66 00 00 30 00>,
    s2: <Buffer 61 61 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
  }
]
```
所以原因是第一个字段由于长度设置错误，写入了第二个char在内存中的数据
