### ISSUE TITLE
同样都是相对路径但是却显示找不到指定的模块

### ISSUE THREAD

**Issue by iceyxx222** [zhangyuang/node-ffi-rs#57]
项目:
- demo
  - ocr
    - OCR_Module.dll 
    - index.js 
  - index.js

demo下的index,js：

const path = require('path')
const { load, DataType, open, close } = require('ffi-rs')
const dynamicLib = './ocr/OCR_Module.dll'
open({
	library: 'ocr',
	path: dynamicLib
})
load({
	library: 'ocr',
	funcName: 'start',
	retType: DataType.Void,
	paramsType: [],
	paramsValue: []
})
close('ocr')

node index.js 调用显示找不到指定的模块

但是在ocr文件夹下调用node index.js，就正常了，没有报错

ocr文件夹下的index.js唯一的区别就在于这里 const dynamicLib = './OCR_Module.dll' ，路径的引入

所以为什么都是相对路径却显示找不到路径，试了绝对路径也不行

**Comment by zhangyuang** [comment]
参考https://github.com/zhangyuang/node-ffi-rs/issues/43

**Comment by iceyxx222** [comment]
已解决 将dll所在目录添加至环境变量即可

**Comment by TNTrocket** [comment]
@iceyxx6 怎么添加至环境变量

**Comment by iceyxx6** [comment]
@TNTrocket 我项目的添加方式供你参考  process.env.Path += `;${path.join(process.cwd(), '/dll所在目录')}`

**Comment by TNTrocket** [comment]
@iceyxx6 谢谢了，这个可以了
