### ISSUE TITLE
Confusing DataType and RetType

### ISSUE THREAD

**Issue by aidv** [zhangyuang/node-ffi-rs#6]
Great library. I'm having a lot of fun with it, but...

It seems like RetType has a few more types than DataType. Why?

Also, DataType does not seem to exist in your code, but ParamsType does. Why?

Your docs use DataType but the code doesn't have that. Why?

Void type doesn't exist in DataType, but it exists in RetType. Why?

So many questions. Please, clear this for me.

Also, if you need help, guide me and I'll improve and contribute to the library as me and my collegue chug along working with it for our application.

Thanks.

**Comment by zhangyuang** [comment]
Since rettype and paramstype have too many similarities. In the new version so I decided to use Datatype for both. Even though they are not exactly equal. This is a breaking change.

**Comment by aidv** [comment]
I see. So Void and Object no longer exists in the new version?

**Comment by zhangyuang** [comment]
DataType also support void.

If you want to use Object, you can write object directly like

```
const person = {
  name: 'tom',
  age: 23,
}
const personObj = load({
  library: 'libsum',
  funcName: 'getStruct',
  retType: {
    name: DataType.String,
    age: DataType.I32,
  },
  paramsType: [{
    name: DataType.String,
    age: DataType.I32,
  }],
  paramsValue: [person]
})
```

**Comment by aidv** [comment]
I see. Object makes sense.

But look at this, this is your code in the NPM package:

![image](https://github.com/zhangyuang/node-ffi-rs/assets/5313040/1aa228a3-b029-45bd-a3f4-605ca8869d20)

**Comment by zhangyuang** [comment]
It looks like I updated the code and didn't release a new version, I'll be releasing him immediately

**Comment by aidv** [comment]
Thanks.

Do you have Telegram? Me and my collegue will use your library extensively for our commercial application, and for future applications.

We'll gladly help improve it when possible so other can enjoy it too.

We should keep in touch and ensure that this library doesn't die like all other FFI libraries for nodejs.

**Comment by zhangyuang** [comment]
Ok, i will register a telegram account in a moment，you guys can also contact me in a github issue or qq email and I'll respond immediately!

**Comment by aidv** [comment]
Where do I find your email?

**Comment by zhangyuang** [comment]
569105585@qq.com If you use WeChat, you can also add my WeChat!

**Comment by zhangyuang** [comment]
The latest version has been released

**Comment by aidv** [comment]
Thanks, the update is working.

I don't have WeChat unfortunately.

Is there a different way I can contact you?

**Comment by zhangyuang** [comment]
you can contact me at github issue，i will receive reminder email
