### ISSUE TITLE
[BUG] Crash when the retType doesn't correspond to the return type of the function

### ISSUE THREAD

**Issue by ultimaj** [zhangyuang/node-ffi-rs#64]
## Current ffi-rs version

"ffi-rs": "^1.0.88"

## Current Node.js arch

v22.4.1

## Descibe your problem in detail

The application is crashed when I try to get a char* which, I guess, is null. When I call the function with Datatype.External in retType, return nothing. When I call it with DataType.String in retType, get the field except if it doesn't exist.

API of the DLL :

char* CreateMessage();
int SetField(char*, char*, char*);
char* getField(char*, char*); 

```typescript
const message = load({
    library: "lib",
    funcName: "CreateMessage",
    retType: DataType.External,
    paramsType: [],
    paramsValue: []
  })

// OK : the file is created

const add_field_result = load({
        library: "lib",
        funcName: "SetField",
        retType: DataType.I32,
        paramsType: [DataType.External, DataType.String, DataType.String],
        paramsValue: [message, "TEST_FIELD", "TEST"]
      })

// the dll function returns 1 to indicate that the field "TEST_FIELD" is created with the value "TEST"

const result = load({
        library: "lib",
        funcName: "GetField",
        retType: DataType.String,
        paramsType: [DataType.External, DataType.String],
        paramsValue: [message, "TEST_FIELD"]
      })

// result = "TEST"

const result = load({
        library: "lib",
        funcName: "GetField",
        retType: DataType.External,
        paramsType: [DataType.External, DataType.String],
        paramsValue: [message, "TEST_FIELD"]
      })

// result = {}

// KO : the field doesn't exist

const result = load({
        library: "lib",
        funcName: "GetField",
        retType: DataType.String,
        paramsType: [DataType.External, DataType.String],
        paramsValue: [message, "TEST_FIELD_2"]
      })

// got a crash of the application, even if I place the load() function into a try...catch

const result = load({
        library: "lib",
        funcName: "GetField",
        retType: DataType.External,
        paramsType: [DataType.External, DataType.String],
        paramsValue: [message, "TEST_FIELD 2"]
      })

// result = {}

```

## What's your expect result

I don't have access to the code of the DLL, but it seems that the functions use the char* as a string (for example the name of the field and its content) and as a real pointer for the message.

However, your load() function seems to can't cast the char* into a DataType.External, only into a DataType.String for GetField() function. In the case of the char* return by GetField() function is, I guess again, null, the load function can't cast it into a DataType.String and kill the process.

It's weird because the load() function works with CreateMessage() function and I can get the char* into a DataType.External.

**Comment by zhangyuang** [comment]
It looks like the `GetField` returns a null pointer when you use `DataType.String` as retType that cause a crash.

When retType is `DataType.External` it only stores and returns a pointer but doesn't access it.

**Comment by ultimaj** [comment]
Oh ok, thank you for your response ! Does it have any solution to know if the DataType.External is a null pointer or if it points to a value ?

**Comment by zhangyuang** [comment]
You can write a c function to check it

```
if (ptr == NULL) {
    // ptr is a null pointer
    printf("Pointer is NULL\n");
} else {
    // ptr is not a null pointer
    printf("Pointer is not NULL\n");
}
```

Compile it to a dynamic library and call it by `ffi-rs`

**Comment by ultimaj** [comment]
Thank you very much for your answers. I'll try your solution and hope to close this issue ! :smile:
