### ISSUE TITLE
 [help wanted] Error cannot find xx function with enum return

### ISSUE THREAD

**Issue by Moon1102** [zhangyuang/node-ffi-rs#65]
## Current ffi-rs version
1.0.88

## Current Node.js arch

Node v20.15.0 x64 win32

## Descibe your problem in detail
If I create a c# test.dll with the following code：
```
namespace A 
{
    public class B {
       public enum Res {  
           Ok = 0,
           Error= 1,
       }

         [DllImport("c.dll")]
         public static extern B.Res GetStatus(out ulong key);
    }
}
```
And use test.dll in Nodejs with Electron:
```
open({
      library: 'A.B', // key
      path: 'src/main/dll/test.dll' // path （I'm sure it's the right path.）
    })
    const r = load({
      library: "A.B", // path to the dynamic library file
      funcName: 'GetStatus', // the name of the function to call
      retType: DataType.U64,
      paramsType:[DataType.U64],
      paramsValue:[BigInt(11)],
      freeResultMemory: true, 
    })
``` 
After run, the console show ```called `Result::unwrap()` on an `Err` value: Error { status: Unknown, reason: "Cannot find \"GetStatus\" function in shared library", maybe_raw: 0x0 }```
## What's your expect result
I am wondering if this DllImport annotated method just can't be called by nodejs or is there something wrong with the ```library, retType``` , etc. parameters in the method I used above? I'm new to nodejs ffi so please help me if you can

**Comment by zhangyuang** [comment]
The error tips is clearly，you have not export c function in dynamic library，please read related c# document to figure out how to export it
