### ISSUE TITLE
Filling a buffer inside the parameters

### ISSUE THREAD

**Issue by aidv** [zhangyuang/node-ffi-rs#7]
I have this piece of code in my DLL:

```
void myFunc(double bufferToFill[3])
{
  bufferToFill[0] = -0.5;
  bufferToFill[1] = 7.5;
  bufferToFill[2] = 3;
}
```

I want to fill the `bufferToFill` buffer from the DLL to my NodeJS app.

I use the following, NodeJS code which is not working.

```
var toFill = new Array(3).fill(0)

const res = load({
      library: "myDLL",
      funcName: "myFunc",
      retType: DataType.Void,

      paramsType: [DataType.DoubleArray],
      paramsValue: [bufferToFill],
})
```

The output is just a bunch of 0 (zero).

Any idea on how to make this work?

**Comment by zhangyuang** [comment]
where you print the output?

**Comment by zhangyuang** [comment]
```js
extern "C" void bufferToFill(double bufferToFill[3]) {
  bufferToFill[0] = -0.5;
  bufferToFill[1] = 7.5;
  bufferToFill[2] = 3;
  printf("%f", bufferToFill[0]);
}

```
My output is -0.500000

**Comment by aidv** [comment]
Yes, inside the DLL it is correct, but inside the NodeJS app, it's incorrect.

```
var bufferToFill= new Array(3).fill(0)

const res = load({
      library: "myDLL",
      funcName: "myFunc",
      retType: DataType.Void,

      paramsType: [DataType.DoubleArray],
      paramsValue: [bufferToFill],
})

console.log(bufferToFill) //prints: [0,0,0]
```

**Comment by zhangyuang** [comment]
you can not modify js valuememory in c libary directly，you should return a new array which is better



发自我的iPhone


------------------ Original ------------------
From: aidv ***@***.***&gt;
Date: Tue,Oct 17,2023 10:01 PM
To: zhangyuang/node-ffi-rs ***@***.***&gt;
Cc: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] Filling a buffer inside the parameters(Issue #7)





 
Yes, inside the DLL it is correct, but inside the NodeJS app, it's incorrect.
 var bufferToFill= new Array(3).fill(0) const res = load({       library: "myDLL",       funcName: "myFunc",       retType: DataType.Void,       paramsType: [DataType.DoubleArray],       paramsValue: [bufferToFill], }) console.log(bufferToFill) //prints: [0,0,0]

**Comment by aidv** [comment]
Ok thanks.

Is it possible to add this feature?

**Comment by zhangyuang** [comment]
i will try it later，but it doesn‘t always succeed，and it's not a safe operation



发自我的iPhone


------------------ Original ------------------
From: aidv ***@***.***&gt;
Date: Tue,Oct 17,2023 10:28 PM
To: zhangyuang/node-ffi-rs ***@***.***&gt;
Cc: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] Filling a buffer inside the parameters(Issue #7)





 
Ok thanks.
 
Is it possible to add this feature?

**Comment by aidv** [comment]
Thanks. It's worth trying maybe.

**Comment by endrigo-fantastsoft** [comment]
I need this feature too. Several libraries I use were built this way. For example, libraries where its return is an integer representing the execution status and receiving two pointers, one a string and the other an integer.

**Comment by zhangyuang** [comment]
In the latest version, `ffi-rs` support modify buffer data in place like 

```c
extern int modifyData(char* buffer) {
    // modify buffer data in place
}
```

```js
const arr = Buffer.alloc(200) // create buffer
const res = load({
  library: "libsum",
  funcName: "modifyData",
  retType: DataType.I32,
  paramsType: [
    DataType.U8Array
  ],
  paramsValue: [arr]
})
console.log(arr) // buffer data can be updated
```
