### ISSUE TITLE
Warning on multiple callbacks. 多次回调时报

### ISSUE THREAD

**Issue by ToDreamAndDream** [zhangyuang/node-ffi-rs#72]
![image](https://github.com/user-attachments/assets/1d1c4bb6-541b-4c85-8ab2-6faee8c58a86)
It has been added “runInNewThread: true”,but a warning will still be given
已经添加了 runInNewThread: true还是会报警告
``` C
// C端代码
//// dllmain.cpp : 定义 DLL 应用程序的入口点。
#include "pch.h"
#include <functional>
#include <iostream>


extern "C"  _declspec(dllexport)  void add(int a, int b, void (*callback)(int)) {

	std::cout << "Number: " << (a + b) << std::endl;
	int a1 = 1;

	while (a1 < 10) {
		std::cout << "Number: " << (a1 + b) << std::endl;
		a1 = a1 + 1;
		callback(a1);
	}
	
}
```

**Comment by zhangyuang** [comment]
fix in 1.0.92

**Comment by ToDreamAndDream** [comment]
## “freePointer ” will cause the process to exit abnormally
freePointer 会导致进程异常退出
同时，不释放指针内存，程序也会一直等待回调不会正常退出

callback在ffi-napi上，node13的版本是正常的，但是14+就不行了，所以我需要一个找到一个合适的库替换它，实现监听打印机的状态回调😀 
``` js
let funcExternal;

const callbackFunc = async (sum) => {
  console.log(sum, "----");

  setTimeout(() => {
    freePointer({
      paramsType: [
        funcConstructor({
          paramsType: [DataType.I32],
          retType: DataType.Void,
        }),
      ],
      paramsValue: funcExternal,
      pointerType: 1,
    });
  }, 2000);

  if (sum === 10) {
    close("libsum");
  }
};

funcExternal = createPointer({
  paramsType: [
    funcConstructor({
      paramsType: [DataType.I32],
      retType: DataType.Void,
    }),
  ],
  paramsValue: [callbackFunc],
});
console.log([2, 3, unwrapPointer(funcExternal)[0]]);

const r = load({
  library: "libsum",
  funcName: "add", // 要调用的 method
  retType: DataType.Void, // 返回值的类型
  paramsType: [DataType.I32, DataType.I32, DataType.External], // 参数的类型
  paramsValue: [2, 3, ...unwrapPointer(funcExternal)], // 实际的参数值
  runInNewThread: true,
});

console.log(r);

setTimeout(() => {
  console.log(r);
}, 5000);

```

**Comment by zhangyuang** [comment]
如果你的callback会被多次调用则不需要freePointer它，此时进程也不需要退出



发自我的iPhone


------------------ 原始邮件 ------------------
From: XCNYMG ***@***.***&gt;
发送时间: 09/12/2024, 09:34
To: zhangyuang/node-ffi-rs ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] Warning on multiple callbacks. 多次回调时报 (Issue #72)





 
“freePointer ” will cause the process to exit abnormally
 
freePointer 会导致进程异常退出
 同时，不释放指针内存，程序也会一直等待回调不会正常退出
 
callback在ffi-napi上，node13的版本是正常的，但是14+就不行了，所以我需要一个找到一个合适的库替换它，实现监听打印机的状态回调😀
 let funcExternal; const callbackFunc = async (sum) =&gt; {   console.log(sum, "----");   setTimeout(() =&gt; {     freePointer({       paramsType: [         funcConstructor({           paramsType: [DataType.I32],           retType: DataType.Void,         }),       ],       paramsValue: funcExternal,       pointerType: 1,     });   }, 2000);   if (sum === 10) {     close("libsum");   } }; funcExternal = createPointer({   paramsType: [     funcConstructor({       paramsType: [DataType.I32],       retType: DataType.Void,     }),   ],   paramsValue: [callbackFunc], }); console.log([2, 3, unwrapPointer(funcExternal)[0]]); const r = load({   library: "libsum",   funcName: "add", // 要调用的 method   retType: DataType.Void, // 返回值的类型   paramsType: [DataType.I32, DataType.I32, DataType.External], // 参数的类型   paramsValue: [2, 3, ...unwrapPointer(funcExternal)], // 实际的参数值   runInNewThread: true, }); console.log(r); setTimeout(() =&gt; {   console.log(r); }, 5000);

**Comment by ToDreamAndDream** [comment]
那是不是也能理解为freePointer其实不太适合函数释放，其它基础类型的指针我没测，不知道是不是也会导致进程异常退出，主要是这个异常退出不知道是怎么回事。
我先在需求上试试，有问题 再反馈哈，谢谢您

**Comment by zhangyuang** [comment]
常驻的应用不需要释放，执行一次就销毁的函数需要



发自我的iPhone


------------------ 原始邮件 ------------------
From: XCNYMG ***@***.***&gt;
发送时间: 09/12/2024, 10:52
To: zhangyuang/node-ffi-rs ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] Warning on multiple callbacks. 多次回调时报 (Issue #72)





 
那是不是也能理解为freePointer其实不太适合函数释放，其它基础类型的指针我没测，不知道是不是也会导致进程异常退出，主要是这个异常退出不知道是怎么回事。
 我先在需求上试试，有问题 再反馈哈，谢谢您
