### ISSUE TITLE
Missing dynamic RTL on Windows

### ISSUE THREAD

**Issue by rozmansi** [zhangyuang/node-ffi-rs#75]
## Current ffi-rs version

Print current Node.js info with the following code

$ cat node_modules/ffi-rs/package.json
```json
{
  "name": "ffi-rs",
  "version": "1.0.94",
  "main": "index.js",
  "types": "index.d.ts",
  "description": "A module written in Rust and N-API provides interface (FFI) features for Node.js",
  "napi": {
    "name": "ffi-rs",
    "triples": {
      "additional": [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "aarch64-unknown-linux-musl",
        "arm-unknown-linux-gnueabihf",
        "i686-pc-windows-msvc",
        "x86_64-unknown-linux-musl",
        "aarch64-pc-windows-msvc"
      ]
    }
  },
  "author": "zhangyuang",
  "homepage": "https://github.com/zhangyuang/node-ffi-rs#readme",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zhangyuang/node-ffi-rs.git"
  },
  "keywords": [
    "ffi",
    "rust",
    "node.js",
    "napi"
  ],
  "files": [
    "index.js",
    "index.d.ts",
    "README.md"
  ],
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "@napi-rs/cli": "^2.15.2",
    "@types/node": "^20.8.7",
    "benny": "^3.7.1",
    "conventional-changelog-cli": "^4.1.0",
    "esno": "^4.0.0",
    "ffi-napi": "^4.0.3",
    "koa": "^2.14.2",
    "shelljs": "^0.8.5",
    "typescript": "^5.4.5"
  },
  "scripts": {
    "artifacts": "napi artifacts",
    "build:c": "node scripts/compile.js",
    "build:dev": "env=development node scripts/build.js",
    "build": "node scripts/build.js",
    "publish:npm": "node scripts/publish.js",
    "test": "esno ./test.ts",
    "changelog": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add . && git commit -m \"docs: update changelog.md\" && git push origin master",
    "pub": "npm version patch && git push origin master --tags && npm run changelog",
    "pub:alpha": "npm version prerelease --preid=alpha && git push origin master --tags"
  },
  "optionalDependencies": {
    "@yuuang/ffi-rs-darwin-arm64": "1.0.94",
    "@yuuang/ffi-rs-darwin-x64": "1.0.94",
    "@yuuang/ffi-rs-linux-arm-gnueabihf": "1.0.94",
    "@yuuang/ffi-rs-linux-arm64-gnu": "1.0.94",
    "@yuuang/ffi-rs-linux-arm64-musl": "1.0.94",
    "@yuuang/ffi-rs-linux-x64-gnu": "1.0.94",
    "@yuuang/ffi-rs-linux-x64-musl": "1.0.94",
    "@yuuang/ffi-rs-win32-arm64-msvc": "1.0.94",
    "@yuuang/ffi-rs-win32-ia32-msvc": "1.0.94",
    "@yuuang/ffi-rs-win32-x64-msvc": "1.0.94"
  }
}
```

$ ls node_modules/@yuuang
```
ffi-rs-win32-ia32-msvc  ffi-rs-win32-x64-msvc
```

## Current Node.js arch

Print current Node.js info with the following code

$ node -e "console.log(process.arch, process.platform)"
```
x64 win32
```

## Descibe your problem in detail

When application is launched on a vanilla Windows 10 x64 PC, the application does not start.
![image](https://github.com/user-attachments/assets/0fd7ce1b-b58f-4f30-92cb-1dcc38bdaa45)

The `resources\app.asar.unpacked\node_modules\@yuuang\ffi-rs-win32-x64-msvc\ffi-rs.win32-x64-msvc.node` is present, but it won't load as `VCRUNTIME140.dll` is not a part of Windows. This file is installed with Visual Studio C Runtime Libraries separately.

## What's your expect result

The application to work on an out-of-the-box Windows 10 or later without additional dependencies.

Can you please compile the `ffi-rs.win32-*-msvc.node` files to use _static_ RTL? Not _dynamic_, please?

**Comment by zhangyuang** [comment]
There is no relationship with static RTL, provide reproduce code or ref #43

**Comment by zhangyuang** [comment]
I am unsure `ffi-rs` or dynamic library depending on Visual Studio. I will check it

**Comment by rozmansi** [comment]
You can use [Dependency Walker](https://dependencywalker.com/) or any PE viewer to see the `ffi-rs.win32-x64-msvc.node` file is really a .dll file, and it is depending on (but not only on) `VCRUNTIME140.dll`, `api-ms-win-crt-heap-l1-1-0.dll`, `api-ms-win-crt-string-l1-1-0.dll` and `api-ms-win-crt-runtime-l1-1-0.dll` which are all not standard on Windows. These are installed by [Visual C Runtimes](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) separately.

**Comment by zhangyuang** [comment]
I compiled the static link in ffi-rs@1.0.95, you can try it

**Comment by rozmansi** [comment]
Thank you. It works! That was awesome.
