### ISSUE TITLE
Object/Struct not working

### ISSUE THREAD

**Issue by aidv** [zhangyuang/node-ffi-rs#8]
I have a DLL that does the following:
```
typedef struct
{
     int aa, bb;
     double kk;
} retStruct;


__declspec(dllexport) retStruct createMyStruct(int a)
{
     retStruct ptr;
     ptr.aa = a;
     ptr.bb = -4;
     ptr.kk = 0.02415;
     fprintf(stderr, "ptr.aa = %d\n", ptr.aa);
     fprintf(stderr, "ptr.bb = %d\n", ptr.bb);
     fprintf(stderr, "ptr.kk = %1.14lf\n", ptr.kk);
     return ptr;
}
```

My NodeJS code does the following:
```
var aVar = 2

const res = load({
    library: 'myDLL',
    funcName: 'createMyStruct',
    retType: {
        aa: DataType.I32,
        bb: DataType.I32,
        kk: DataType.Double
    },

    paramsType: [DataType.I32],

    paramsValue: [aVar]
})
```

My app crashes with following error:
```
thread '<unnamed>' panicked at src\lib.rs:579:19:

stack backtrace:
   0:     0x7ffe5b44d9a3 - napi_register_module_v1
   1:     0x7ffe5b41a11b - <unknown>
   2:     0x7ffe5b446202 - napi_register_module_v1
   3:     0x7ffe5b44fec4 - napi_register_module_v1
   4:     0x7ffe5b44fb4f - napi_register_module_v1
   5:     0x7ffe5b450466 - napi_register_module_v1
   6:     0x7ffe5b450023 - napi_register_module_v1
   7:     0x7ffe5b44ffa9 - napi_register_module_v1
   8:     0x7ffe5b44ff94 - napi_register_module_v1
   9:     0x7ffe5b455135 - napi_register_module_v1
  10:     0x7ffe5b416458 - <unknown>
  11:     0x7ff6091d29fe - napi_is_detached_arraybuffer
  12:     0x7ff609c9cd08 - v8::EmbedderStateScope::~EmbedderStateScope
  13:     0x7b245fed07bc - <unknown>
  14:     0x7b245fe4bca9 - <unknown>
  15:     0x7b245fe4bca9 - <unknown>
  16:     0x7b245ff26119 - <unknown>
  17:     0x7b245fe497f1 - <unknown>
  18:     0x7b245ff79de4 - <unknown>
  19:     0x7b245fe4bca9 - <unknown>
  20:     0x7b245fe4bca9 - <unknown>
  21:     0x7b245fe4bca9 - <unknown>
  22:     0x7b245ff26119 - <unknown>
  23:     0x7b245fe497f1 - <unknown>
  24:     0x7b245ff79de4 - <unknown>
  25:     0x7b245fe4bca9 - <unknown>
  26:     0x7b245fe4bca9 - <unknown>
  27:     0x7b245fe4bca9 - <unknown>
  28:     0x7b24401b5934 - <unknown>
  29:     0x7b24401b9505 - <unknown>
  30:     0x7b24401b5bb5 - <unknown>
  31:     0x7b2440150ffe - <unknown>
  32:     0x7b24401b609a - <unknown>
  33:     0x7b2440150ffe - <unknown>
  34:     0x7b24401529e9 - <unknown>
  35:     0x7b245fe4a41c - <unknown>
  36:     0x7b245fe4a01b - <unknown>
  37:     0x7ff609cc0d23 - v8::EmbedderStateScope::~EmbedderStateScope
  38:     0x7ff609c855b7 - v8::Function::Call
  39:     0x7ff60853f3f5 - node::CallbackScope::CallbackScope
  40:     0x7ff60853f7f9 - node::MakeCallback
  41:     0x7ff60853f67e - node::MakeCallback
  42:     0x7ff60853f50a - node::MakeCallback
  43:     0x7ff606c8a3a1 - cppgc::internal::CrossThreadPersistentRegion::NodesInUse
  44:     0x7ff606bd9057 - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame> >::__throw_length_error
  45:     0x7ff606bd8efe - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame> >::__throw_length_error
  46:     0x7ff606bbfb82 - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame> >::__throw_length_error
  47:     0x7ff606bbf862 - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame> >::__throw_length_error
  48:     0x7ff606bfb22a - std::Cr::vector<v8::CpuProfileDeoptInfo,std::Cr::allocator<v8::CpuProfileDeoptInfo> >::__alloc
  49:     0x7ff607f6acee - uv_fs_get_result
  50:     0x7ff60a2b1ec0 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow
  51:     0x7ff60a3616c7 - Cr_z_crc32_z
  52:     0x7ff60a2b2cb8 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow
  53:     0x7ff60a2d791f - Cr_z_crc32_z
  54:     0x7ff60a27ab18 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow
  55:     0x7ff60a34fa05 - Cr_z_crc32_z
  56:     0x7ff60a289885 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow
  57:     0x7ff608046b95 - uv_fs_get_result
  58:     0x7ff6085cb1d3 - uv_sleep
  59:     0x7ff60801d8bd - uv_fs_get_result
  60:     0x7ff6078f29e2 - node::GetEnvironmentIsolateData
  61:     0x7ff6078f4641 - node::GetEnvironmentIsolateData
  62:     0x7ff6078efe49 - node::GetEnvironmentIsolateData
  63:     0x7ff606d9031e - v8::metrics::LongTaskStats::LongTaskStats
  64:     0x7ff606d919cd - v8::metrics::LongTaskStats::LongTaskStats
  65:     0x7ff606d9139a - v8::metrics::LongTaskStats::LongTaskStats
  66:     0x7ff606d8d908 - v8::metrics::LongTaskStats::LongTaskStats
  67:     0x7ff606d8da4b - v8::metrics::LongTaskStats::LongTaskStats
  68:     0x7ff606b2aa5d - cppgc::SourceLocation::SourceLocation
  69:     0x7ff60a70f462 - Cr_z_crc32_z
  70:     0x7ffe8dff7344 - BaseThreadInitThunk
  71:     0x7ffe8fc626b1 - RtlUserThreadStart
[16456:1017/182257.352:ERROR:crashpad_client_win.cc(844)] not connected
```

What is going on and how to fix it?

**Comment by zhangyuang** [comment]
Struct field type support string and i32 at now，i will support other type in tomorrow



发自我的iPhone


------------------ Original ------------------
From: aidv ***@***.***&gt;
Date: Wed,Oct 18,2023 0:27 AM
To: zhangyuang/node-ffi-rs ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [zhangyuang/node-ffi-rs] Object/Struct not working (Issue #8)





 
I have a DLL that does the following:
 typedef struct {      int aa, bb;      double kk; } retStruct; __declspec(dllexport) retStruct createMyStruct(int a) {      retStruct ptr;      ptr.aa = a;      ptr.bb = -4;      ptr.kk = 0.02415;      fprintf(stderr, "ptr.aa = %d\n", ptr.aa);      fprintf(stderr, "ptr.bb = %d\n", ptr.bb);      fprintf(stderr, "ptr.kk = %1.14lf\n", ptr.kk);      return ptr; }  
My NodeJS code does the following:
 var aVar = 2 const res = load({     library: 'myDLL',     funcName: 'createMyStruct',     retType: {         aa: DataType.I32,         bb: DataType.I32,         kk: DataType.Double     },     paramsType: [DataType.I32],     paramsValue: [aVar] })  
My app crashes with following error:
 thread '<unnamed&gt;' panicked at src\lib.rs:579:19: stack backtrace:    0:     0x7ffe5b44d9a3 - napi_register_module_v1    1:     0x7ffe5b41a11b - <unknown&gt;    2:     0x7ffe5b446202 - napi_register_module_v1    3:     0x7ffe5b44fec4 - napi_register_module_v1    4:     0x7ffe5b44fb4f - napi_register_module_v1    5:     0x7ffe5b450466 - napi_register_module_v1    6:     0x7ffe5b450023 - napi_register_module_v1    7:     0x7ffe5b44ffa9 - napi_register_module_v1    8:     0x7ffe5b44ff94 - napi_register_module_v1    9:     0x7ffe5b455135 - napi_register_module_v1   10:     0x7ffe5b416458 - <unknown&gt;   11:     0x7ff6091d29fe - napi_is_detached_arraybuffer   12:     0x7ff609c9cd08 - v8::EmbedderStateScope::~EmbedderStateScope   13:     0x7b245fed07bc - <unknown&gt;   14:     0x7b245fe4bca9 - <unknown&gt;   15:     0x7b245fe4bca9 - <unknown&gt;   16:     0x7b245ff26119 - <unknown&gt;   17:     0x7b245fe497f1 - <unknown&gt;   18:     0x7b245ff79de4 - <unknown&gt;   19:     0x7b245fe4bca9 - <unknown&gt;   20:     0x7b245fe4bca9 - <unknown&gt;   21:     0x7b245fe4bca9 - <unknown&gt;   22:     0x7b245ff26119 - <unknown&gt;   23:     0x7b245fe497f1 - <unknown&gt;   24:     0x7b245ff79de4 - <unknown&gt;   25:     0x7b245fe4bca9 - <unknown&gt;   26:     0x7b245fe4bca9 - <unknown&gt;   27:     0x7b245fe4bca9 - <unknown&gt;   28:     0x7b24401b5934 - <unknown&gt;   29:     0x7b24401b9505 - <unknown&gt;   30:     0x7b24401b5bb5 - <unknown&gt;   31:     0x7b2440150ffe - <unknown&gt;   32:     0x7b24401b609a - <unknown&gt;   33:     0x7b2440150ffe - <unknown&gt;   34:     0x7b24401529e9 - <unknown&gt;   35:     0x7b245fe4a41c - <unknown&gt;   36:     0x7b245fe4a01b - <unknown&gt;   37:     0x7ff609cc0d23 - v8::EmbedderStateScope::~EmbedderStateScope   38:     0x7ff609c855b7 - v8::Function::Call   39:     0x7ff60853f3f5 - node::CallbackScope::CallbackScope   40:     0x7ff60853f7f9 - node::MakeCallback   41:     0x7ff60853f67e - node::MakeCallback   42:     0x7ff60853f50a - node::MakeCallback   43:     0x7ff606c8a3a1 - cppgc::internal::CrossThreadPersistentRegion::NodesInUse   44:     0x7ff606bd9057 - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame&gt; &gt;::__throw_length_error   45:     0x7ff606bd8efe - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame&gt; &gt;::__throw_length_error   46:     0x7ff606bbfb82 - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame&gt; &gt;::__throw_length_error   47:     0x7ff606bbf862 - std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame&gt; &gt;::__throw_length_error   48:     0x7ff606bfb22a - std::Cr::vector<v8::CpuProfileDeoptInfo,std::Cr::allocator<v8::CpuProfileDeoptInfo&gt; &gt;::__alloc   49:     0x7ff607f6acee - uv_fs_get_result   50:     0x7ff60a2b1ec0 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow   51:     0x7ff60a3616c7 - Cr_z_crc32_z   52:     0x7ff60a2b2cb8 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow   53:     0x7ff60a2d791f - Cr_z_crc32_z   54:     0x7ff60a27ab18 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow   55:     0x7ff60a34fa05 - Cr_z_crc32_z   56:     0x7ff60a289885 - cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow   57:     0x7ff608046b95 - uv_fs_get_result   58:     0x7ff6085cb1d3 - uv_sleep   59:     0x7ff60801d8bd - uv_fs_get_result   60:     0x7ff6078f29e2 - node::GetEnvironmentIsolateData   61:     0x7ff6078f4641 - node::GetEnvironmentIsolateData   62:     0x7ff6078efe49 - node::GetEnvironmentIsolateData   63:     0x7ff606d9031e - v8::metrics::LongTaskStats::LongTaskStats   64:     0x7ff606d919cd - v8::metrics::LongTaskStats::LongTaskStats   65:     0x7ff606d9139a - v8::metrics::LongTaskStats::LongTaskStats   66:     0x7ff606d8d908 - v8::metrics::LongTaskStats::LongTaskStats   67:     0x7ff606d8da4b - v8::metrics::LongTaskStats::LongTaskStats   68:     0x7ff606b2aa5d - cppgc::SourceLocation::SourceLocation   69:     0x7ff60a70f462 - Cr_z_crc32_z   70:     0x7ffe8dff7344 - BaseThreadInitThunk   71:     0x7ffe8fc626b1 - RtlUserThreadStart [16456:1017/182257.352:ERROR:crashpad_client_win.cc(844)] not connected  
What is going on and how to fix it?

**Comment by aidv** [comment]
Ok, Thank you.

Please add all of the data types to struct field.

Also, it is possible to add even more types? Like uint, long, etc?

**Comment by zhangyuang** [comment]
Ok, all of these types look like they will be able to be added. I will support as soon as possible

**Comment by aidv** [comment]
Ok thank you very much sir.

**Comment by zhangyuang** [comment]
The latest version of struct supports double, i32array, doubleArray, stringArray, please refer to the latest readme for more details. retTypeLen is deprecated in the latest version, and arrayConstructor is added to specify the legal length of the returned array.

**Comment by zhangyuang** [comment]
the correct d.ts type will be refined in the next release
