### ISSUE TITLE
c++多维数组结构体 

### ISSUE THREAD

**Issue by xu455255849** [zhangyuang/node-ffi-rs#80]
const ref = require('ref-napi');
const ArrayType = require('ref-array-napi');
const StructType = require('ref-struct-napi')
// 定义数据类型
const doubleType = ref.types.double;
const uint32Type = ref.types.uint32;
// 定义数组类型
const DoubleArray25 = ArrayType(doubleType, 25);
const DoubleArray12x25 = ArrayType(DoubleArray25, 12);
const DoubleArray9x12x25 = ArrayType(DoubleArray12x25, 9);
const Uint32Array5508 = ArrayType(uint32Type, 5508);
const hsv_input = StructType({
  luma_lut: DoubleArray9x12x25,
  sat_lut: DoubleArray9x12x25,
  hue_lut: DoubleArray9x12x25,
});
const clut_output = StructType({
  clut_output: Uint32Array5508,
});

ffi-rs能构造类似的结构体 吗？ 还是得保留const ref = require('ref-napi');
const ArrayType = require('ref-array-napi');
const StructType = require('ref-struct-napi')这些库

**Comment by xu455255849** [comment]
我已经在 ffi-napi 完成类似的逻辑，想要迁移过来，但是 文档并不详尽，
这个库的资料也比较少
 let lib = null;
  try {
    lib = ffi.Library(join(process.env.DLL, 'algClutLib'), {
      'Hsv2Clut_array': ['void', [ref.refType(hsv_input), ref.refType(clut_output)]],
    })
  } catch (err) {
    log.info(err)
  }

**Comment by zhangyuang** [comment]
🤔目前不支持在 ffi-rs 中创建二维数组这种复杂结构，不过你可以在c语言侧创建对应的二维数组结构然后把指针返回给 ffi-rs，后续再传递给其他c函数调用

**Comment by xu455255849** [comment]
> 🤔目前不支持在 ffi-rs 中创建二维数组这种复杂结构，不过你可以在c语言侧创建对应的二维数组结构然后把指针返回给 ffi-rs，后续再传递给其他c函数调用

好吧，，我手头没有c++源代码，三方提供DLL库，只能调 不能改，暂时先不考虑迁移了
