### ISSUE TITLE
How to Utilize a Pointer Combining Two Structs?

### ISSUE THREAD

**Issue by HoseonChu** [zhangyuang/node-ffi-rs#86]
I am using a third-party C++ library that provides the following structures 

typedef struct
{
    short x, y, dir;
    unsigned char kind;
} MINUTIA;

typedef struct {
    short nNumber;
    MINUTIA item[150];
} MINUTIAE, *LPMINUTIAE; 

I need to create an LPMINUTIAE pointer using these structures. Could you provide guidance or an example on how to achieve this with ffi-rs? I'm not quite sure how to proceed.

Thank you in advance for your help!

**Comment by zhangyuang** [comment]
ffi-rs doesn't support struct array at this time. I will support it later

**Comment by zhangyuang** [comment]
I will support it this week

**Comment by zhangyuang** [comment]
Support structArray in ffi-rs@1.2.0

https://github.com/zhangyuang/node-ffi-rs/blob/master/tests/struct.ts#L78

https://github.com/zhangyuang/node-ffi-rs/blob/master/cpp/sum.cpp#L259

**Comment by HoseonChu** [comment]
@zhangyuang Oh, thank you! I didn't expect this improvement to be implemented so quickly. I’ll start using it right away and share the test results with you soon. Thanks a lot!"

**Comment by HoseonChu** [comment]
@zhangyuang  I just tested it, and it works great. The pointer creation and restorePointer functions also work perfectly. Thank you so much!

**Comment by HoseonChu** [comment]
@zhangyuang  I just tested it, and it works great. The pointer creation and restorePointer functions also work perfectly. Thank you so much!
