### ISSUE TITLE
关于buffer的问题

### ISSUE THREAD

**Issue by snowflake-x** [zhangyuang/node-ffi-rs#87]
如果buffer返回值为结构体指针 此时如何获取该结构体内容？

**Comment by zhangyuang** [comment]
restorePointer



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: snowflake ***@***.***&gt;
发送时间: 2024年12月26日 13:24
收件人: zhangyuang/node-ffi-rs ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/node-ffi-rs] 关于buffer的问题 (Issue #87)





 
如果buffer返回值为结构体指针 此时如何获取该结构体内容？
